export interface RoadmapWeek {
  week: number;
  patternId: string;
  patternName: string;
  objective: string;
  structuralNecessity: string;
  newProblems: number;
  reviewProblems: number;
  deliverables: string[];
  problems: { name: string; number?: number; difficulty: "Easy" | "Medium" | "Hard"; day: string; insight: string }[];
}

export const roadmap: RoadmapWeek[] = [
  {
    week: 1,
    patternId: "hashmap",
    patternName: "Arrays & Hashing",
    objective: "Master O(1) lookup patterns and array traversal fundamentals.",
    structuralNecessity: "When frequency, existence, or pairing matters, hash maps reduce O(n²) to O(n).",
    newProblems: 12,
    reviewProblems: 0,
    deliverables: [
      "12 derivation logs completed",
      "1 LTS pattern document written",
      "Can articulate: 'When I need O(1) existence/frequency lookup, I use a hash map because...'"
    ],
    problems: [
      { name: "Two Sum", number: 1, difficulty: "Easy", day: "Monday", insight: "Complement lookup reduces O(n²) to O(n)." },
      { name: "Contains Duplicate", number: 217, difficulty: "Easy", day: "Monday", insight: "Set existence is O(1)." },
      { name: "Valid Anagram", number: 242, difficulty: "Easy", day: "Tuesday", insight: "Character frequency counting." },
      { name: "Group Anagrams", number: 49, difficulty: "Medium", day: "Tuesday", insight: "Sorted string is the canonical key." },
      { name: "Top K Frequent Elements", number: 347, difficulty: "Medium", day: "Tuesday", insight: "Count first, then select top K." },
      { name: "Product of Array Except Self", number: 238, difficulty: "Medium", day: "Wednesday", insight: "Prefix/suffix products without division." },
      { name: "Valid Sudoku", number: 36, difficulty: "Medium", day: "Wednesday", insight: "Hash sets for row/col/box constraints." },
      { name: "Encode and Decode Strings", number: 271, difficulty: "Medium", day: "Wednesday", insight: "Length-prefixed serialization." },
      { name: "Longest Consecutive Sequence", number: 128, difficulty: "Medium", day: "Thursday", insight: "Hash set for O(n) sequence detection." },
      { name: "Intersection of Two Arrays", number: 349, difficulty: "Easy", day: "Thursday", insight: "Basic set intersection." },
      { name: "Intersection of Two Arrays II", number: 350, difficulty: "Easy", day: "Thursday", insight: "Frequency map intersection." },
      { name: "Move Zeroes", number: 283, difficulty: "Easy", day: "Friday", insight: "Two-pointer in-place rearrangement." },
    ],
  },
  {
    week: 2,
    patternId: "twopointers",
    patternName: "Two Pointers",
    objective: "Master pair-wise processing from both ends and monotonic array exploitation.",
    structuralNecessity: "Sorted/monotonic ordering allows skipping impossible candidates, reducing search space.",
    newProblems: 10,
    reviewProblems: 3,
    deliverables: [
      "10 new derivation logs + 3 review logs",
      "2 LTS pattern documents total",
      "Can articulate: 'When the array is sorted or monotonic, two pointers reduce the problem from O(n²) to O(n) because...'"
    ],
    problems: [
      { name: "Valid Palindrome", number: 125, difficulty: "Easy", day: "Monday", insight: "Left/right pointer comparison." },
      { name: "Two Sum II", number: 167, difficulty: "Medium", day: "Monday", insight: "Sorted array two-pointer." },
      { name: "3Sum", number: 15, difficulty: "Medium", day: "Tuesday", insight: "Fix one, two-pointer the rest." },
      { name: "3Sum Closest", number: 16, difficulty: "Medium", day: "Tuesday", insight: "Variation with target comparison." },
      { name: "Container With Most Water", number: 11, difficulty: "Medium", day: "Tuesday", insight: "Moving shorter line is optimal." },
      { name: "Trapping Rain Water", number: 42, difficulty: "Hard", day: "Wednesday", insight: "Water depends on min(leftMax, rightMax)." },
      { name: "Remove Duplicates from Sorted Array", number: 26, difficulty: "Easy", day: "Wednesday", insight: "In-place deduplication." },
      { name: "Remove Element", number: 27, difficulty: "Easy", day: "Wednesday", insight: "In-place removal." },
      { name: "Sort Colors", number: 75, difficulty: "Medium", day: "Thursday", insight: "Dutch National Flag. Three pointers for O(n) in-place." },
      { name: "Boats to Save People", number: 881, difficulty: "Medium", day: "Thursday", insight: "Greedy two-pointer pairing." },
    ],
  },
  {
    week: 3,
    patternId: "slidingwindow",
    patternName: "Sliding Window",
    objective: "Master subarray/substring optimization with dynamic expansion/contraction.",
    structuralNecessity: "When brute force is O(n²) and the problem asks for a contiguous subarray, a window achieves O(n).",
    newProblems: 10,
    reviewProblems: 3,
    deliverables: [
      "10 new derivation logs + 3 review logs",
      "3 LTS pattern documents total",
      "Can articulate: 'When brute force is O(n²) and contiguous, sliding window achieves O(n)...'"
    ],
    problems: [
      { name: "Best Time to Buy and Sell Stock", number: 121, difficulty: "Easy", day: "Monday", insight: "Minimum-so-far creates the window." },
      { name: "Longest Substring Without Repeating Characters", number: 3, difficulty: "Medium", day: "Monday", insight: "Window starts at last duplicate + 1." },
      { name: "Permutation in String", number: 567, difficulty: "Medium", day: "Tuesday", insight: "Fixed-size window with frequency map." },
      { name: "Minimum Window Substring", number: 76, difficulty: "Hard", day: "Tuesday", insight: "Variable window with constraint satisfaction." },
      { name: "Sliding Window Maximum", number: 239, difficulty: "Hard", day: "Tuesday", insight: "Monotonic deque gives O(n)." },
      { name: "Subarray Product Less Than K", number: 713, difficulty: "Medium", day: "Wednesday", insight: "Counting subarrays with product constraint." },
      { name: "Longest Repeating Character Replacement", number: 424, difficulty: "Medium", day: "Wednesday", insight: "Window with at most k replacements." },
      { name: "Max Consecutive Ones III", number: 1004, difficulty: "Medium", day: "Wednesday", insight: "Flip at most k zeros." },
      { name: "Number of Substrings With Only 1s", number: 1513, difficulty: "Medium", day: "Thursday", insight: "Counting using window property." },
      { name: "Fruit Into Baskets", number: 904, difficulty: "Medium", day: "Thursday", insight: "At most 2 distinct types." },
    ],
  },
  {
    week: 4,
    patternId: "stack",
    patternName: "Stack",
    objective: "Master LIFO processing, monotonic stacks, and deferred computation patterns.",
    structuralNecessity: "When you need to defer processing or maintain monotonic property (next greater/smaller), stack provides O(1) push/pop with ordered access.",
    newProblems: 10,
    reviewProblems: 3,
    deliverables: [
      "10 new derivation logs + 3 review logs",
      "4 LTS pattern documents total",
      "Can articulate: 'When I need next greater/smaller element, a monotonic stack gives O(n) because each element is pushed and popped exactly once...'"
    ],
    problems: [
      { name: "Valid Parentheses", number: 20, difficulty: "Easy", day: "Monday", insight: "Stack matches nested pairs." },
      { name: "Min Stack", number: 155, difficulty: "Medium", day: "Monday", insight: "Auxiliary stack for minimum tracking." },
      { name: "Evaluate Reverse Polish Notation", number: 150, difficulty: "Medium", day: "Tuesday", insight: "Stack-based evaluation." },
      { name: "Daily Temperatures", number: 739, difficulty: "Medium", day: "Tuesday", insight: "Monotonic decreasing stack." },
      { name: "Largest Rectangle in Histogram", number: 84, difficulty: "Hard", day: "Tuesday", insight: "Stack tracks increasing heights." },
      { name: "Next Greater Element I", number: 496, difficulty: "Easy", day: "Wednesday", insight: "Basic monotonic stack." },
      { name: "Next Greater Element II", number: 503, difficulty: "Medium", day: "Wednesday", insight: "Circular array - process 2n elements." },
      { name: "Car Fleet", number: 853, difficulty: "Medium", day: "Wednesday", insight: "Stack for collision detection." },
      { name: "Online Stock Span", number: 901, difficulty: "Medium", day: "Thursday", insight: "Monotonic stack for span calculation." },
      { name: "Remove All Adjacent Duplicates in String II", number: 1209, difficulty: "Medium", day: "Thursday", insight: "Stack with count tracking." },
    ],
  },
  {
    week: 5,
    patternId: "binarysearch",
    patternName: "Binary Search",
    objective: "Master divide-by-half search on monotonic predicates.",
    structuralNecessity: "When the answer space is monotonic (if X works, all > X work), binary search reduces O(n) to O(log n).",
    newProblems: 12,
    reviewProblems: 3,
    deliverables: [
      "12 new derivation logs + 3 review logs",
      "5 LTS pattern documents total",
      "Can articulate: 'When the answer space is monotonic, binary search on the answer gives O(log n) because we discard half at each step...'"
    ],
    problems: [
      { name: "Binary Search", number: 704, difficulty: "Easy", day: "Monday", insight: "Discard half each step." },
      { name: "Search in Rotated Sorted Array", number: 33, difficulty: "Medium", day: "Monday", insight: "One half is always sorted." },
      { name: "Find Minimum in Rotated Sorted Array", number: 153, difficulty: "Medium", day: "Monday", insight: "Compare mid to right." },
      { name: "Search a 2D Matrix", number: 74, difficulty: "Medium", day: "Tuesday", insight: "Treat as 1D sorted array." },
      { name: "Koko Eating Bananas", number: 875, difficulty: "Medium", day: "Tuesday", insight: "Binary search on answer space." },
      { name: "Find Minimum in Rotated Sorted Array II", number: 154, difficulty: "Medium", day: "Tuesday", insight: "Duplicates break the guarantee." },
      { name: "Time Based Key-Value Store", number: 981, difficulty: "Medium", day: "Wednesday", insight: "Binary search on timestamps." },
      { name: "Search Insert Position", number: 35, difficulty: "Easy", day: "Wednesday", insight: "Lower bound." },
      { name: "Find Peak Element", number: 162, difficulty: "Medium", day: "Wednesday", insight: "A peak must exist." },
      { name: "Search for a Range", number: 34, difficulty: "Medium", day: "Thursday", insight: "Find first and last occurrence." },
      { name: "Sqrt(x)", number: 69, difficulty: "Easy", day: "Thursday", insight: "Binary search on integer answer." },
      { name: "Capacity To Ship Packages Within D Days", number: 1011, difficulty: "Medium", day: "Thursday", insight: "Binary search on capacity." },
    ],
  },
  {
    week: 6,
    patternId: "linkedlist",
    patternName: "Linked List",
    objective: "Master pointer manipulation, fast/slow pointers, and in-place restructuring.",
    structuralNecessity: "When sequential access with O(1) insertion/deletion is required, linked lists provide pointer-based manipulation without array shifting.",
    newProblems: 12,
    reviewProblems: 3,
    deliverables: [
      "12 new derivation logs + 3 review logs",
      "6 LTS pattern documents total",
      "Can articulate: 'When I need O(1) insertion/deletion or pointer manipulation, a linked list allows restructuring without shifting elements...'"
    ],
    problems: [
      { name: "Reverse Linked List", number: 206, difficulty: "Easy", day: "Monday", insight: "Three-pointer reversal." },
      { name: "Merge Two Sorted Lists", number: 21, difficulty: "Easy", day: "Monday", insight: "Dummy head pattern." },
      { name: "Linked List Cycle", number: 141, difficulty: "Easy", day: "Tuesday", insight: "Floyd's fast/slow." },
      { name: "Reorder List", number: 143, difficulty: "Medium", day: "Tuesday", insight: "Find middle, reverse, merge." },
      { name: "Remove Nth Node From End of List", number: 19, difficulty: "Medium", day: "Tuesday", insight: "Fast/slow pointer with gap." },
      { name: "Merge K Sorted Lists", number: 23, difficulty: "Hard", day: "Wednesday", insight: "Priority queue or divide-and-conquer." },
      { name: "Add Two Numbers", number: 2, difficulty: "Medium", day: "Wednesday", insight: "Digit-by-digit addition with carry." },
      { name: "Copy List with Random Pointer", number: 138, difficulty: "Medium", day: "Wednesday", insight: "Interleaving copy." },
      { name: "Rotate List", number: 61, difficulty: "Medium", day: "Thursday", insight: "Find kth from end, rewire." },
      { name: "Partition List", number: 86, difficulty: "Medium", day: "Thursday", insight: "Separate into two lists, rejoin." },
      { name: "Remove Duplicates from Sorted List II", number: 82, difficulty: "Medium", day: "Thursday", insight: "Skip all duplicates." },
      { name: "Odd Even Linked List", number: 328, difficulty: "Medium", day: "Friday", insight: "Separate and rejoin." },
    ],
  },
  {
    week: 7,
    patternId: "review",
    patternName: "Review & Consolidation 1",
    objective: "No new patterns. Interleaved review of Weeks 1-6. Strengthen weak areas.",
    structuralNecessity: "Re-derivation from memory is the only valid test of proceduralization. Review is not repetition; it is myelination reinforcement.",
    newProblems: 0,
    reviewProblems: 12,
    deliverables: [
      "12 review logs",
      "All 6 LTS documents updated",
      "Can identify the correct pattern for 70% of Phase 1 problems within 2 minutes"
    ],
    problems: [
      { name: "Re-derive 2 problems from Week 1 (Arrays & Hashing)", difficulty: "Medium", day: "Monday", insight: "From scratch without looking." },
      { name: "Re-derive 2 problems from Week 2 (Two Pointers)", difficulty: "Medium", day: "Tuesday", insight: "Identify pattern from statement alone." },
      { name: "Re-derive 2 problems from Week 3 (Sliding Window)", difficulty: "Medium", day: "Tuesday", insight: "Identify pattern from statement alone." },
      { name: "Re-derive 2 problems from Week 4 (Stack)", difficulty: "Medium", day: "Wednesday", insight: "Write inclusive/exclusive templates from memory." },
      { name: "Re-derive 2 problems from Week 5 (Binary Search)", difficulty: "Medium", day: "Wednesday", insight: "Write inclusive/exclusive templates from memory." },
      { name: "Re-derive 2 problems from Week 6 (Linked List)", difficulty: "Medium", day: "Thursday", insight: "Draw pointer states step by step." },
      { name: "Pattern Identification Drill: 4 problem statements", difficulty: "Medium", day: "Friday", insight: "Identify pattern BEFORE reading full description." },
    ],
  },
  {
    week: 8,
    patternId: "trees",
    patternName: "Trees - Basics",
    objective: "Master hierarchical traversal: DFS (recursive/iterative), BFS, and BST properties.",
    structuralNecessity: "Hierarchical data with parent-child relationships requires tree traversal. Recursion naturally maps to tree depth.",
    newProblems: 12,
    reviewProblems: 3,
    deliverables: [
      "12 new derivation logs + 3 review logs",
      "7 LTS pattern documents total",
      "Can articulate: 'When data is hierarchical, tree traversal (DFS/BFS) is necessary because the parent-child relationship defines the search space...'"
    ],
    problems: [
      { name: "Invert Binary Tree", number: 226, difficulty: "Easy", day: "Monday", insight: "Pre-order swap." },
      { name: "Maximum Depth of Binary Tree", number: 104, difficulty: "Easy", day: "Monday", insight: "Post-order max+1." },
      { name: "Same Tree", number: 100, difficulty: "Easy", day: "Monday", insight: "Simultaneous traversal." },
      { name: "Subtree of Another Tree", number: 572, difficulty: "Medium", day: "Tuesday", insight: "Serialize or recursive check." },
      { name: "Lowest Common Ancestor of a Binary Search Tree", number: 235, difficulty: "Medium", day: "Tuesday", insight: "BST property exploitation." },
      { name: "Binary Tree Level Order Traversal", number: 102, difficulty: "Medium", day: "Tuesday", insight: "BFS with queue." },
      { name: "Validate Binary Search Tree", number: 98, difficulty: "Medium", day: "Wednesday", insight: "In-order traversal or range checking." },
      { name: "Kth Smallest Element in a BST", number: 230, difficulty: "Medium", day: "Wednesday", insight: "In-order traversal." },
      { name: "Construct Binary Tree from Preorder and Inorder", number: 105, difficulty: "Medium", day: "Wednesday", insight: "Preorder gives root, inorder gives partition." },
      { name: "Path Sum", number: 112, difficulty: "Easy", day: "Thursday", insight: "DFS with accumulator." },
      { name: "Binary Tree Maximum Path Sum", number: 124, difficulty: "Hard", day: "Thursday", insight: "Post-order DFS. Need both local and global max." },
      { name: "Symmetric Tree", number: 101, difficulty: "Easy", day: "Thursday", insight: "Mirror traversal." },
    ],
  },
];

// Phase 2: Weeks 9-16
export const roadmapPhase2: RoadmapWeek[] = [
  {
    week: 9,
    patternId: "heap",
    patternName: "Heap / Priority Queue",
    objective: "Master dynamic min/max extraction and top-K selection.",
    structuralNecessity: "When you need the smallest or largest element dynamically as data arrives, a heap provides O(log n) insertion and extraction.",
    newProblems: 10,
    reviewProblems: 3,
    deliverables: [
      "10 new derivation logs + 3 review logs",
      "8 LTS pattern documents total",
      "Can articulate: 'When I need dynamic min/max or top K elements, a heap gives O(log n) insertion/extraction because the parent-child ordering guarantees the root is always the extremum...'"
    ],
    problems: [
      { name: "Kth Largest Element in an Array", number: 215, difficulty: "Medium", day: "Monday", insight: "Min-heap of size k." },
      { name: "Top K Frequent Elements", number: 347, difficulty: "Medium", day: "Monday", insight: "Count first, then min-heap of size k." },
      { name: "Find Median from Data Stream", number: 295, difficulty: "Hard", day: "Tuesday", insight: "Two heaps: max-heap for lower half, min-heap for upper half." },
      { name: "Merge K Sorted Lists", number: 23, difficulty: "Hard", day: "Tuesday", insight: "K-way merge with min-heap." },
      { name: "Task Scheduler", number: 621, difficulty: "Medium", day: "Tuesday", insight: "Most frequent task dictates minimum idle time." },
      { name: "Reorganize String", number: 767, difficulty: "Medium", day: "Wednesday", insight: "Max-heap by frequency. Place highest freq chars first." },
      { name: "Sort Characters By Frequency", number: 451, difficulty: "Medium", day: "Wednesday", insight: "Max-heap by frequency, then reconstruct." },
      { name: "Meeting Rooms II", number: 253, difficulty: "Medium", day: "Wednesday", insight: "Min-heap tracks end times of ongoing meetings." },
      { name: "Last Stone Weight", number: 1046, difficulty: "Easy", day: "Thursday", insight: "Max-heap for heaviest stones." },
      { name: "K Closest Points to Origin", number: 973, difficulty: "Medium", day: "Thursday", insight: "Max-heap of size k by distance." },
    ],
  },
  {
    week: 10,
    patternId: "backtracking",
    patternName: "Backtracking",
    objective: "Master combinatorial search: subsets, permutations, and constraint satisfaction.",
    structuralNecessity: "When the problem asks for ALL valid configurations (not just one), and the search space is exponential, backtracking with pruning is necessary.",
    newProblems: 12,
    reviewProblems: 3,
    deliverables: [
      "12 new derivation logs + 3 review logs",
      "9 LTS pattern documents total",
      "Can articulate: 'When the problem asks for all permutations/subsets/combinations, backtracking explores the decision tree depth-first, pruning branches that violate constraints...'"
    ],
    problems: [
      { name: "Subsets", number: 78, difficulty: "Medium", day: "Monday", insight: "Every node is a valid subset." },
      { name: "Subsets II", number: 90, difficulty: "Medium", day: "Monday", insight: "Sort first, skip duplicates." },
      { name: "Permutations", number: 46, difficulty: "Medium", day: "Tuesday", insight: "Used array prevents reuse." },
      { name: "Permutations II", number: 47, difficulty: "Medium", day: "Tuesday", insight: "Sort first, skip duplicates at same depth." },
      { name: "Combination Sum", number: 39, difficulty: "Medium", day: "Tuesday", insight: "Can reuse same element. Start from current index." },
      { name: "Combination Sum II", number: 40, difficulty: "Medium", day: "Wednesday", insight: "Each number used once. Sort and skip duplicates." },
      { name: "Combination Sum III", number: 216, difficulty: "Medium", day: "Wednesday", insight: "Exactly k numbers summing to n." },
      { name: "Palindrome Partitioning", number: 131, difficulty: "Medium", day: "Wednesday", insight: "Check palindrome at each split point." },
      { name: "Letter Combinations of a Phone Number", number: 17, difficulty: "Medium", day: "Thursday", insight: "Cartesian product via backtracking." },
      { name: "Generate Parentheses", number: 22, difficulty: "Medium", day: "Thursday", insight: "Track open and close count. Prune invalid." },
      { name: "N-Queens", number: 51, difficulty: "Hard", day: "Thursday", insight: "Conflict sets prune branches: row, col, diag." },
      { name: "Sudoku Solver", number: 37, difficulty: "Hard", day: "Friday", insight: "Backtrack with constraint propagation." },
    ],
  },
  {
    week: 11,
    patternId: "graphs",
    patternName: "Graphs",
    objective: "Master BFS, DFS, topological sort, and union-find on networks.",
    structuralNecessity: "When data is a non-hierarchical network with explicit connections, graph traversal is the only way to explore relationships between nodes.",
    newProblems: 12,
    reviewProblems: 3,
    deliverables: [
      "12 new derivation logs + 3 review logs",
      "10 LTS pattern documents total",
      "Can articulate: 'When data is a network of connected nodes, BFS finds shortest paths and DFS explores connectivity; topological sort orders dependencies...'"
    ],
    problems: [
      { name: "Number of Islands", number: 200, difficulty: "Medium", day: "Monday", insight: "Grid DFS marks connected land." },
      { name: "Clone Graph", number: 133, difficulty: "Medium", day: "Monday", insight: "Visited map prevents cycles." },
      { name: "Course Schedule", number: 207, difficulty: "Medium", day: "Tuesday", insight: "Topological sort via Kahn (in-degree)." },
      { name: "Course Schedule II", number: 210, difficulty: "Medium", day: "Tuesday", insight: "Return valid ordering or empty." },
      { name: "Pacific Atlantic Water Flow", number: 417, difficulty: "Medium", day: "Tuesday", insight: "Reverse DFS from oceans." },
      { name: "Surrounded Regions", number: 130, difficulty: "Medium", day: "Wednesday", insight: "Reverse: mark un-surrounded from border." },
      { name: "Rotting Oranges", number: 994, difficulty: "Medium", day: "Wednesday", insight: "Multi-source BFS." },
      { name: "Word Ladder", number: 127, difficulty: "Hard", day: "Wednesday", insight: "BFS on word graph." },
      { name: "Evaluate Division", number: 399, difficulty: "Medium", day: "Thursday", insight: "Graph with edge weights. DFS for query." },
      { name: "Cheapest Flights Within K Stops", number: 787, difficulty: "Medium", day: "Thursday", insight: "Bellman-Ford or modified Dijkstra." },
      { name: "Is Graph Bipartite?", number: 785, difficulty: "Medium", day: "Thursday", insight: "Two-color BFS/DFS." },
      { name: "Redundant Connection", number: 684, difficulty: "Medium", day: "Friday", insight: "Union-find to detect cycle." },
    ],
  },
  {
    week: 12,
    patternId: "dp1d",
    patternName: "DP 1D",
    objective: "Master optimal substructure with a single state dimension.",
    structuralNecessity: "When a problem asks for max/min/count on a sequence and the optimal solution depends only on previous states, 1D DP compresses exponential recursion into linear time.",
    newProblems: 12,
    reviewProblems: 3,
    deliverables: [
      "12 new derivation logs + 3 review logs",
      "11 LTS pattern documents total",
      "Can articulate: 'When the optimal solution at index i depends only on solutions at i-1, i-2, etc., 1D DP achieves O(n) by storing and reusing subproblem solutions...'"
    ],
    problems: [
      { name: "Climbing Stairs", number: 70, difficulty: "Easy", day: "Monday", insight: "Fibonacci recurrence." },
      { name: "House Robber", number: 198, difficulty: "Medium", day: "Monday", insight: "Rob or skip. dp[i] = max(dp[i-1], dp[i-2] + nums[i])." },
      { name: "House Robber II", number: 213, difficulty: "Medium", day: "Tuesday", insight: "Circular: split into two linear subproblems." },
      { name: "Coin Change", number: 322, difficulty: "Medium", day: "Tuesday", insight: "Unbounded knapsack. dp[i] = min coins for amount i." },
      { name: "Maximum Subarray", number: 53, difficulty: "Medium", day: "Tuesday", insight: "Kadane's: local max at i = max(nums[i], local_max[i-1] + nums[i])." },
      { name: "Longest Increasing Subsequence", number: 300, difficulty: "Medium", day: "Wednesday", insight: "dp[i] = LIS ending at index i." },
      { name: "Word Break", number: 139, difficulty: "Medium", day: "Wednesday", insight: "dp[i] = can segment s[0..i)." },
      { name: "Decode Ways", number: 91, difficulty: "Medium", day: "Wednesday", insight: "Each digit and each valid two-digit combo branches the count." },
      { name: "Partition Equal Subset Sum", number: 416, difficulty: "Medium", day: "Thursday", insight: "0/1 knapsack: can we pick elements that sum to total/2?" },
      { name: "Target Sum", number: 494, difficulty: "Medium", day: "Thursday", insight: "Transform to subset sum: find subsets with value (sum+target)/2." },
      { name: "Best Time to Buy and Sell Stock", number: 121, difficulty: "Easy", day: "Thursday", insight: "Track min price so far; profit at each day is price - min." },
      { name: "Best Time to Buy and Sell Stock with Cooldown", number: 309, difficulty: "Medium", day: "Friday", insight: "State machine: held, sold, rested." },
    ],
  },
  {
    week: 13,
    patternId: "dp2d",
    patternName: "DP 2D",
    objective: "Master optimal substructure with two state dimensions (grid, two strings).",
    structuralNecessity: "When decisions depend on two dimensions (grid position, two sequences), 2D DP stores the optimal solution for every pair of prefix states.",
    newProblems: 10,
    reviewProblems: 3,
    deliverables: [
      "10 new derivation logs + 3 review logs",
      "12 LTS pattern documents total",
      "Can articulate: 'When decisions depend on two dimensions, dp[i][j] stores the optimal solution for prefixes ending at i and j, built from previously computed neighbors...'"
    ],
    problems: [
      { name: "Unique Paths", number: 62, difficulty: "Medium", day: "Monday", insight: "Paths = up + left." },
      { name: "Longest Common Subsequence", number: 1143, difficulty: "Medium", day: "Monday", insight: "Match extends diagonal; mismatch takes max of top or left." },
      { name: "Edit Distance", number: 72, difficulty: "Hard", day: "Tuesday", insight: "Replace/delete/insert." },
      { name: "Minimum Path Sum", number: 64, difficulty: "Medium", day: "Tuesday", insight: "dp[j] = min path sum to reach cell (i,j)." },
      { name: "Triangle", number: 120, difficulty: "Medium", day: "Tuesday", insight: "Bottom-up: dp[j] = triangle[i][j] + min(dp[j], dp[j+1])." },
      { name: "Interleaving String", number: 97, difficulty: "Medium", day: "Wednesday", insight: "dp[i][j] = can s3[0..i+j) be formed from s1[0..i) and s2[0..j)." },
      { name: "Maximal Square", number: 221, difficulty: "Medium", day: "Wednesday", insight: "dp[i][j] = side length of largest square of 1s ending at (i,j)." },
      { name: "Dungeon Game", number: 174, difficulty: "Hard", day: "Wednesday", insight: "Bottom-up: dp[j] = min health needed at (i,j) to survive to princess." },
      { name: "Distinct Subsequences", number: 115, difficulty: "Hard", day: "Thursday", insight: "dp[j] = count of t[0..j) as subsequence in s processed so far." },
      { name: "Longest Palindromic Subsequence", number: 516, difficulty: "Medium", day: "Thursday", insight: "Match extends by 2 from inner diagonal." },
    ],
  },
  {
    week: 14,
    patternId: "intervals",
    patternName: "Intervals",
    objective: "Master range coordination: merging, overlapping, and scheduling.",
    structuralNecessity: "When problems involve time ranges or start/end points, sorting by start time transforms chaos into a scanable sequence where adjacency implies non-overlap.",
    newProblems: 10,
    reviewProblems: 3,
    deliverables: [
      "10 new derivation logs + 3 review logs",
      "13 LTS pattern documents total",
      "Can articulate: 'When ranges need coordination, sorting by start time makes non-overlapping intervals adjacent, allowing a single scan to detect conflicts...'"
    ],
    problems: [
      { name: "Merge Intervals", number: 56, difficulty: "Medium", day: "Monday", insight: "Sort then scan." },
      { name: "Non-overlapping Intervals", number: 435, difficulty: "Medium", day: "Monday", insight: "Greedy by end time." },
      { name: "Insert Interval", number: 57, difficulty: "Medium", day: "Tuesday", insight: "Find insertion point, merge overlaps." },
      { name: "Minimum Number of Arrows to Burst Balloons", number: 452, difficulty: "Medium", day: "Tuesday", insight: "Sort by end, shoot at end of first balloon." },
      { name: "Interval List Intersections", number: 986, difficulty: "Medium", day: "Tuesday", insight: "Two-pointer on sorted lists." },
      { name: "Remove Covered Intervals", number: 1288, difficulty: "Medium", day: "Wednesday", insight: "Sort by start desc, end asc. Track max end." },
      { name: "Meeting Rooms", number: 252, difficulty: "Easy", day: "Wednesday", insight: "Sort by start, check if next start < prev end." },
      { name: "Partition Labels", number: 763, difficulty: "Medium", day: "Wednesday", insight: "Greedy: extend current partition to last occurrence of any char in it." },
      { name: "Set Intersection Size At Least Two", number: 757, difficulty: "Hard", day: "Thursday", insight: "Greedy: pick two rightmost points of each interval." },
      { name: "Employee Free Time", number: 759, difficulty: "Medium", day: "Thursday", insight: "Merge all intervals, find gaps." },
    ],
  },
  {
    week: 15,
    patternId: "bits",
    patternName: "Bit Manipulation",
    objective: "Master binary representations for parity, uniqueness, and powers of 2.",
    structuralNecessity: "When operations are on powers of 2, parity, or uniqueness, bitwise ops provide O(1) primitives that arithmetic cannot match.",
    newProblems: 8,
    reviewProblems: 3,
    deliverables: [
      "8 new derivation logs + 3 review logs",
      "14 LTS pattern documents total",
      "Can articulate: 'When dealing with parity, powers of 2, or uniqueness via XOR, bitwise operations are O(1) primitives that arithmetic cannot match...'"
    ],
    problems: [
      { name: "Single Number", number: 136, difficulty: "Easy", day: "Monday", insight: "XOR cancels pairs." },
      { name: "Number of 1 Bits", number: 191, difficulty: "Easy", day: "Monday", insight: "n & (n-1) clears lowest set bit." },
      { name: "Missing Number", number: 268, difficulty: "Easy", day: "Tuesday", insight: "XOR indices and values." },
      { name: "Counting Bits", number: 338, difficulty: "Easy", day: "Tuesday", insight: "dp[i] = dp[i >> 1] + (i & 1)." },
      { name: "Reverse Bits", number: 190, difficulty: "Easy", day: "Tuesday", insight: "Shift result left, take LSB of n, shift n right." },
      { name: "Power of Two", number: 231, difficulty: "Easy", day: "Wednesday", insight: "n & (n-1) == 0 for powers of 2." },
      { name: "Sum of Two Integers", number: 371, difficulty: "Medium", day: "Wednesday", insight: "XOR for sum, AND << 1 for carry. Repeat." },
      { name: "Maximum XOR of Two Numbers in an Array", number: 421, difficulty: "Medium", day: "Wednesday", insight: "Trie of prefixes, greedily try to set each bit." },
    ],
  },
  {
    week: 16,
    patternId: "greedy",
    patternName: "Greedy",
    objective: "Master locally optimal choices that lead to globally optimal solutions.",
    structuralNecessity: "When a problem exhibits the greedy-choice property (local optimum is part of global optimum) and optimal substructure, greedy achieves the best possible result without exhaustive search.",
    newProblems: 10,
    reviewProblems: 3,
    deliverables: [
      "10 new derivation logs + 3 review logs",
      "15 LTS pattern documents total",
      "Can articulate: 'When the greedy-choice property holds (local optimum is part of global optimum), making the locally best choice at each step achieves global optimum without exhaustive search...'"
    ],
    problems: [
      { name: "Jump Game", number: 55, difficulty: "Medium", day: "Monday", insight: "Track farthest reachable index." },
      { name: "Jump Game II", number: 45, difficulty: "Medium", day: "Monday", insight: "Min jumps via greedy BFS." },
      { name: "Gas Station", number: 134, difficulty: "Medium", day: "Tuesday", insight: "If total gas >= total cost, a solution exists." },
      { name: "Candy", number: 135, difficulty: "Hard", day: "Tuesday", insight: "Two-pass: left-to-right then right-to-left." },
      { name: "Task Scheduler", number: 621, difficulty: "Medium", day: "Tuesday", insight: "Most frequent task dictates minimum idle time." },
      { name: "Assign Cookies", number: 455, difficulty: "Easy", day: "Wednesday", insight: "Sort both, greedily assign smallest cookie that satisfies child." },
      { name: "Queue Reconstruction by Height", number: 406, difficulty: "Medium", day: "Wednesday", insight: "Sort by height desc, then insert by k." },
      { name: "Remove K Digits", number: 402, difficulty: "Medium", day: "Wednesday", insight: "Monotonic stack: remove larger digits when possible." },
      { name: "Minimum Number of Refueling Stops", number: 871, difficulty: "Hard", day: "Thursday", insight: "Max-heap of passed stations' fuel." },
      { name: "IPO", number: 502, difficulty: "Hard", day: "Thursday", insight: "Select project with max profit among affordable ones." },
    ],
  },
];

// Full combined roadmap
export const fullRoadmap: RoadmapWeek[] = [...roadmap, ...roadmapPhase2];
