// @ts-nocheck
export interface TestCase {
  input: string;
  expected: string;
  args: any[];
  expectedValue: any;
}

export interface Problem {
  id: string;
  patternId: string;
  name: string;
  difficulty: "Easy" | "Medium" | "Hard";
  number: number;
  description: string;
  examples: { input: string; output: string; explanation?: string }[];
  constraints: string[];
  starterCode: string;
  solution: string;
  testCases: TestCase[];
  why: string;
}

export const batch5Problems: Problem[] = [
  // =================== DP 1D ===================
  {
    id: "climbing-stairs",
    patternId: "dp1d",
    name: "Climbing Stairs",
    difficulty: "Easy",
    number: 70,
    description: `You are climbing a staircase. It takes n steps to reach the top. Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?`,
    examples: [
      { input: "n = 2", output: "2", explanation: "1+1 or 2" },
      { input: "n = 3", output: "3", explanation: "1+1+1, 1+2, 2+1" },
    ],
    constraints: ["1 <= n <= 45"],
    starterCode: `/**\n * @param {number} n\n * @return {number}\n */\nvar climbStairs = function(n) {\n    // Write your code here\n    \n};`,
    solution: `var climbStairs = function(n) {\n    if (n <= 2) return n;\n    let a = 1, b = 2;\n    for (let i = 3; i <= n; i++) {\n        const c = a + b;\n        a = b;\n        b = c;\n    }\n    return b;\n};`,
    testCases: [
      { input: "n = 2", expected: "2", args: [2], expectedValue: 2 },
      { input: "n = 3", expected: "3", args: [3], expectedValue: 3 },
      { input: "n = 4", expected: "5", args: [4], expectedValue: 5 },
    ],
    why: "Fibonacci recurrence: ways(n) = ways(n-1) + ways(n-2).",
  },
  {
    id: "house-robber",
    patternId: "dp1d",
    name: "House Robber",
    difficulty: "Medium",
    number: 198,
    description: `You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed. The only constraint is that adjacent houses have security systems connected and it will automatically contact the police if two adjacent houses were broken into on the same night. Given an integer array nums representing the amount of money of each house, return the maximum amount of money you can rob tonight without alerting the police.`,
    examples: [
      { input: "nums = [1,2,3,1]", output: "4", explanation: "Rob house 1 and house 3." },
      { input: "nums = [2,7,9,3,1]", output: "12", explanation: "Rob house 1, 3, and 5." },
    ],
    constraints: ["1 <= nums.length <= 100", "0 <= nums[i] <= 400"],
    starterCode: `/**\n * @param {number[]} nums\n * @return {number}\n */\nvar rob = function(nums) {\n    // Write your code here\n    \n};`,
    solution: `var rob = function(nums) {\n    let prev2 = 0, prev1 = 0;\n    for (const num of nums) {\n        const curr = Math.max(prev1, prev2 + num);\n        prev2 = prev1;\n        prev1 = curr;\n    }\n    return prev1;\n};`,
    testCases: [
      { input: "nums = [1,2,3,1]", expected: "4", args: [[1,2,3,1]], expectedValue: 4 },
      { input: "nums = [2,7,9,3,1]", expected: "12", args: [[2,7,9,3,1]], expectedValue: 12 },
      { input: "nums = [0]", expected: "0", args: [[0]], expectedValue: 0 },
    ],
    why: "DP state tracks max money up to i-th house without alerting police.",
  },
  {
    id: "house-robber-ii",
    patternId: "dp1d",
    name: "House Robber II",
    difficulty: "Medium",
    number: 213,
    description: `You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed. All houses at this place are arranged in a circle. That means the first house is the neighbor of the last one. Given an integer array nums representing the amount of money of each house, return the maximum amount of money you can rob tonight without alerting the police.`,
    examples: [
      { input: "nums = [2,3,2]", output: "3", explanation: "Cannot rob house 1 and 3 together." },
      { input: "nums = [1,2,3,1]", output: "4", explanation: "Rob house 1 and 3." },
    ],
    constraints: ["1 <= nums.length <= 100", "0 <= nums[i] <= 1000"],
    starterCode: `/**\n * @param {number[]} nums\n * @return {number}\n */\nvar rob = function(nums) {\n    // Write your code here\n    \n};`,
    solution: `var rob = function(nums) {\n    if (nums.length === 1) return nums[0];\n    const helper = (arr) => {\n        let a = 0, b = 0;\n        for (const x of arr) {\n            const c = Math.max(b, a + x);\n            a = b;\n            b = c;\n        }\n        return b;\n    };\n    return Math.max(helper(nums.slice(1)), helper(nums.slice(0, -1)));\n};`,
    testCases: [
      { input: "nums = [2,3,2]", expected: "3", args: [[2,3,2]], expectedValue: 3 },
      { input: "nums = [1,2,3,1]", expected: "4", args: [[1,2,3,1]], expectedValue: 4 },
      { input: "nums = [1]", expected: "1", args: [[1]], expectedValue: 1 },
    ],
    why: "Circular constraint splits into two linear House Robber subproblems.",
  },
  {
    id: "coin-change",
    patternId: "dp1d",
    name: "Coin Change",
    difficulty: "Medium",
    number: 322,
    description: `You are given an integer array coins representing coins of different denominations and an integer amount representing a total amount of money. Return the fewest number of coins that you need to make up that amount. If that amount of money cannot be made up by any combination of the coins, return -1.`,
    examples: [
      { input: "coins = [1,2,5], amount = 11", output: "3", explanation: "11 = 5 + 5 + 1" },
      { input: "coins = [2], amount = 3", output: "-1" },
    ],
    constraints: ["1 <= coins.length <= 12", "1 <= coins[i] <= 2^31 - 1", "0 <= amount <= 10^4"],
    starterCode: `/**\n * @param {number[]} coins\n * @param {number} amount\n * @return {number}\n */\nvar coinChange = function(coins, amount) {\n    // Write your code here\n    \n};`,
    solution: `var coinChange = function(coins, amount) {\n    const dp = new Array(amount + 1).fill(Infinity);\n    dp[0] = 0;\n    for (let i = 1; i <= amount; i++) {\n        for (const c of coins) {\n            if (i >= c) dp[i] = Math.min(dp[i], dp[i - c] + 1);\n        }\n    }\n    return dp[amount] === Infinity ? -1 : dp[amount];\n};`,
    testCases: [
      { input: "coins = [1,2,5], amount = 11", expected: "3", args: [[1,2,5], 11], expectedValue: 3 },
      { input: "coins = [2], amount = 3", expected: "-1", args: [[2], 3], expectedValue: -1 },
      { input: "coins = [1], amount = 0", expected: "0", args: [[1], 0], expectedValue: 0 },
    ],
    why: "Unbounded knapsack: dp[i] = min coins to make amount i.",
  },
  {
    id: "maximum-subarray",
    patternId: "dp1d",
    name: "Maximum Subarray",
    difficulty: "Medium",
    number: 53,
    description: `Given an integer array nums, find the subarray with the largest sum, and return its sum.`,
    examples: [
      { input: "nums = [-2,1,-3,4,-1,2,1,-5,4]", output: "6", explanation: "[4,-1,2,1] has the largest sum = 6." },
      { input: "nums = [1]", output: "1" },
    ],
    constraints: ["1 <= nums.length <= 10^5", "-10^4 <= nums[i] <= 10^4"],
    starterCode: `/**\n * @param {number[]} nums\n * @return {number}\n */\nvar maxSubArray = function(nums) {\n    // Write your code here\n    \n};`,
    solution: `var maxSubArray = function(nums) {\n    let max = nums[0], curr = nums[0];\n    for (let i = 1; i < nums.length; i++) {\n        curr = Math.max(nums[i], curr + nums[i]);\n        max = Math.max(max, curr);\n    }\n    return max;\n};`,
    testCases: [
      { input: "nums = [-2,1,-3,4,-1,2,1,-5,4]", expected: "6", args: [[-2,1,-3,4,-1,2,1,-5,4]], expectedValue: 6 },
      { input: "nums = [1]", expected: "1", args: [[1]], expectedValue: 1 },
      { input: "nums = [5,4,-1,7,8]", expected: "23", args: [[5,4,-1,7,8]], expectedValue: 23 },
    ],
    why: "Kadane's: local max at i is either start new or extend previous.",
  },
  {
    id: "longest-increasing-subsequence",
    patternId: "dp1d",
    name: "Longest Increasing Subsequence",
    difficulty: "Medium",
    number: 300,
    description: `Given an integer array nums, return the length of the longest strictly increasing subsequence.`,
    examples: [
      { input: "nums = [10,9,2,5,3,7,101,18]", output: "4", explanation: "[2,3,7,101]" },
      { input: "nums = [0,1,0,3,2,3]", output: "4" },
    ],
    constraints: ["1 <= nums.length <= 2500", "-10^4 <= nums[i] <= 10^4"],
    starterCode: `/**\n * @param {number[]} nums\n * @return {number}\n */\nvar lengthOfLIS = function(nums) {\n    // Write your code here\n    \n};`,
    solution: `var lengthOfLIS = function(nums) {\n    const dp = new Array(nums.length).fill(1);\n    for (let i = 1; i < nums.length; i++) {\n        for (let j = 0; j < i; j++) {\n            if (nums[i] > nums[j]) dp[i] = Math.max(dp[i], dp[j] + 1);\n        }\n    }\n    return Math.max(...dp);\n};`,
    testCases: [
      { input: "nums = [10,9,2,5,3,7,101,18]", expected: "4", args: [[10,9,2,5,3,7,101,18]], expectedValue: 4 },
      { input: "nums = [0,1,0,3,2,3]", expected: "4", args: [[0,1,0,3,2,3]], expectedValue: 4 },
      { input: "nums = [7,7,7,7,7,7,7]", expected: "1", args: [[7,7,7,7,7,7,7]], expectedValue: 1 },
    ],
    why: "dp[i] stores LIS ending at index i; O(n²) base case.",
  },
  {
    id: "word-break",
    patternId: "dp1d",
    name: "Word Break",
    difficulty: "Medium",
    number: 139,
    description: `Given a string s and a dictionary of strings wordDict, return true if s can be segmented into a space-separated sequence of one or more dictionary words.`,
    examples: [
      { input: 's = "leetcode", wordDict = ["leet","code"]', output: "true", explanation: '"leetcode" can be segmented as "leet code".' },
      { input: 's = "applepenapple", wordDict = ["apple","pen"]', output: "true" },
    ],
    constraints: ['1 <= s.length <= 300', '1 <= wordDict.length <= 1000', '1 <= wordDict[i].length <= 20'],
    starterCode: `/**\n * @param {string} s\n * @param {string[]} wordDict\n * @return {boolean}\n */\nvar wordBreak = function(s, wordDict) {\n    // Write your code here\n    \n};`,
    solution: `var wordBreak = function(s, wordDict) {\n    const set = new Set(wordDict);\n    const dp = new Array(s.length + 1).fill(false);\n    dp[0] = true;\n    for (let i = 1; i <= s.length; i++) {\n        for (let j = 0; j < i; j++) {\n            if (dp[j] && set.has(s.substring(j, i))) {\n                dp[i] = true;\n                break;\n            }\n        }\n    }\n    return dp[s.length];\n};`,
    testCases: [
      { input: 's = "leetcode", wordDict = ["leet","code"]', expected: "true", args: ["leetcode", ["leet","code"]], expectedValue: true },
      { input: 's = "catsandog", wordDict = ["cats","dog","sand","and","cat"]', expected: "false", args: ["catsandog", ["cats","dog","sand","and","cat"]], expectedValue: false },
    ],
    why: "dp[i] = true if s[0..i) can be segmented using dictionary words.",
  },
  {
    id: "decode-ways",
    patternId: "dp1d",
    name: "Decode Ways",
    difficulty: "Medium",
    number: 91,
    description: `A message containing letters from A-Z can be encoded into numbers using the following mapping: 'A' -> "1", 'B' -> "2", ... 'Z' -> "26". Given a string s containing only digits, return the number of ways to decode it.`,
    examples: [
      { input: 's = "12"', output: "2", explanation: '"12" could be decoded as "AB" (1 2) or "L" (12).' },
      { input: 's = "226"', output: "3" },
    ],
    constraints: ['1 <= s.length <= 100', 's contains only digits and may contain leading zero(s).'],
    starterCode: `/**\n * @param {string} s\n * @return {number}\n */\nvar numDecodings = function(s) {\n    // Write your code here\n    \n};`,
    solution: `var numDecodings = function(s) {\n    if (s[0] === '0') return 0;\n    let prev2 = 1, prev1 = 1;\n    for (let i = 1; i < s.length; i++) {\n        let curr = 0;\n        if (s[i] !== '0') curr += prev1;\n        const two = parseInt(s.substring(i - 1, i + 1));\n        if (two >= 10 && two <= 26) curr += prev2;\n        prev2 = prev1;\n        prev1 = curr;\n        if (curr === 0) return 0;\n    }\n    return prev1;\n};`,
    testCases: [
      { input: 's = "12"', expected: "2", args: ["12"], expectedValue: 2 },
      { input: 's = "226"', expected: "3", args: ["226"], expectedValue: 3 },
      { input: 's = "0"', expected: "0", args: ["0"], expectedValue: 0 },
    ],
    why: "Each digit and each valid two-digit combo branches the decode count.",
  },
  {
    id: "partition-equal-subset-sum",
    patternId: "dp1d",
    name: "Partition Equal Subset Sum",
    difficulty: "Medium",
    number: 416,
    description: `Given a non-empty array nums containing only positive integers, find if the array can be partitioned into two subsets such that the sum of elements in both subsets is equal.`,
    examples: [
      { input: "nums = [1,5,11,5]", output: "true", explanation: "The array can be partitioned as [1,5,5] and [11]." },
      { input: "nums = [1,2,3,5]", output: "false" },
    ],
    constraints: ["1 <= nums.length <= 200", "1 <= nums[i] <= 100"],
    starterCode: `/**\n * @param {number[]} nums\n * @return {boolean}\n */\nvar canPartition = function(nums) {\n    // Write your code here\n    \n};`,
    solution: `var canPartition = function(nums) {\n    const total = nums.reduce((a, b) => a + b, 0);\n    if (total % 2 !== 0) return false;\n    const target = total / 2;\n    const dp = new Array(target + 1).fill(false);\n    dp[0] = true;\n    for (const num of nums) {\n        for (let i = target; i >= num; i--) {\n            dp[i] = dp[i] || dp[i - num];\n        }\n    }\n    return dp[target];\n};`,
    testCases: [
      { input: "nums = [1,5,11,5]", expected: "true", args: [[1,5,11,5]], expectedValue: true },
      { input: "nums = [1,2,3,5]", expected: "false", args: [[1,2,3,5]], expectedValue: false },
      { input: "nums = [2,2]", expected: "true", args: [[2,2]], expectedValue: true },
    ],
    why: "0/1 knapsack: can we pick elements that sum to total/2?",
  },
  {
    id: "target-sum",
    patternId: "dp1d",
    name: "Target Sum",
    difficulty: "Medium",
    number: 494,
    description: `You are given an integer array nums and an integer target. You want to build an expression out of nums by adding one of the symbols '+' and '-' before each integer in nums and then concatenate all the integers. Return the number of different expressions that you can build, which evaluates to target.`,
    examples: [
      { input: "nums = [1,1,1,1,1], target = 3", output: "5", explanation: "There are 5 ways to assign symbols to make the sum of nums be target 3." },
      { input: "nums = [1], target = 1", output: "1" },
    ],
    constraints: ["1 <= nums.length <= 20", "0 <= nums[i] <= 1000", "0 <= sum(nums[i]) <= 1000", "-1000 <= target <= 1000"],
    starterCode: `/**\n * @param {number[]} nums\n * @param {number} target\n * @return {number}\n */\nvar findTargetSumWays = function(nums, target) {\n    // Write your code here\n    \n};`,
    solution: `var findTargetSumWays = function(nums, target) {\n    const sum = nums.reduce((a, b) => a + b, 0);\n    if (Math.abs(target) > sum || (sum + target) % 2 !== 0) return 0;\n    const subset = (sum + target) / 2;\n    const dp = new Array(subset + 1).fill(0);\n    dp[0] = 1;\n    for (const num of nums) {\n        for (let i = subset; i >= num; i--) {\n            dp[i] += dp[i - num];\n        }\n    }\n    return dp[subset];\n};`,
    testCases: [
      { input: "nums = [1,1,1,1,1], target = 3", expected: "5", args: [[1,1,1,1,1], 3], expectedValue: 5 },
      { input: "nums = [1], target = 1", expected: "1", args: [[1], 1], expectedValue: 1 },
      { input: "nums = [1,2,3], target = 0", expected: "2", args: [[1,2,3], 0], expectedValue: 2 },
    ],
    why: "Transform to subset sum: find subsets with value (sum+target)/2.",
  },
  {
    id: "palindromic-substrings",
    patternId: "dp1d",
    name: "Palindromic Substrings",
    difficulty: "Medium",
    number: 647,
    description: `Given a string s, return the number of palindromic substrings in it. A string is a palindrome when it reads the same backward as forward. A substring is a contiguous sequence of characters within the string.`,
    examples: [
      { input: 's = "abc"', output: "3", explanation: '"a", "b", "c".' },
      { input: 's = "aaa"', output: "6", explanation: '"a", "a", "a", "aa", "aa", "aaa".' },
    ],
    constraints: ['1 <= s.length <= 1000', 's consists of lowercase English letters.'],
    starterCode: `/**\n * @param {string} s\n * @return {number}\n */\nvar countSubstrings = function(s) {\n    // Write your code here\n    \n};`,
    solution: `var countSubstrings = function(s) {\n    let count = 0;\n    const expand = (left, right) => {\n        while (left >= 0 && right < s.length && s[left] === s[right]) {\n            count++;\n            left--;\n            right++;\n        }\n    };\n    for (let i = 0; i < s.length; i++) {\n        expand(i, i);\n        expand(i, i + 1);\n    }\n    return count;\n};`,
    testCases: [
      { input: 's = "abc"', expected: "3", args: ["abc"], expectedValue: 3 },
      { input: 's = "aaa"', expected: "6", args: ["aaa"], expectedValue: 6 },
      { input: 's = "a"', expected: "1", args: ["a"], expectedValue: 1 },
    ],
    why: "Expand around centers: each center generates palindromes.",
  },
  {
    id: "longest-palindromic-substring",
    patternId: "dp1d",
    name: "Longest Palindromic Substring",
    difficulty: "Medium",
    number: 5,
    description: `Given a string s, return the longest palindromic substring in s.`,
    examples: [
      { input: 's = "babad"', output: '"bab"', explanation: '"aba" is also a valid answer.' },
      { input: 's = "cbbd"', output: '"bb"' },
    ],
    constraints: ['1 <= s.length <= 1000', 's consist of only digits and English letters.'],
    starterCode: `/**\n * @param {string} s\n * @return {string}\n */\nvar longestPalindrome = function(s) {\n    // Write your code here\n    \n};`,
    solution: `var longestPalindrome = function(s) {\n    let start = 0, end = 0;\n    const expand = (l, r) => {\n        while (l >= 0 && r < s.length && s[l] === s[r]) {\n            l--;\n            r++;\n        }\n        return r - l - 1;\n    };\n    for (let i = 0; i < s.length; i++) {\n        const len1 = expand(i, i);\n        const len2 = expand(i, i + 1);\n        const len = Math.max(len1, len2);\n        if (len > end - start) {\n            start = i - Math.floor((len - 1) / 2);\n            end = i + Math.floor(len / 2);\n        }\n    }\n    return s.substring(start, end + 1);\n};`,
    testCases: [
      { input: 's = "babad"', expected: '"bab" or "aba"', args: ["babad"], expectedValue: "bab" },
      { input: 's = "cbbd"', expected: '"bb"', args: ["cbbd"], expectedValue: "bb" },
      { input: 's = "a"', expected: '"a"', args: ["a"], expectedValue: "a" },
    ],
    why: "Expand around center to find max palindrome length at each index.",
  },
  {
    id: "delete-and-earn",
    patternId: "dp1d",
    name: "Delete and Earn",
    difficulty: "Medium",
    number: 740,
    description: `You are given an integer array nums. You want to maximize the number of points you get by performing the following operation any number of times: Pick any nums[i] and delete it to earn nums[i] points. Afterwards, you must delete every element equal to nums[i] - 1 and every element equal to nums[i] + 1. Return the maximum number of points you can earn by applying the above operation some number of times.`,
    examples: [
      { input: "nums = [3,4,2]", output: "6", explanation: "Delete 4 to earn 4 points. Consequently, 3 is deleted. Then delete 2 to earn 2 points. 4 + 2 = 6." },
      { input: "nums = [2,2,3,3,3,4]", output: "9", explanation: "Delete 3 to earn 3 points. All 2's and 4's are deleted. Then delete 3 again to earn 3 points. 6 + 3 = 9." },
    ],
    constraints: ["1 <= nums.length <= 2 * 10^4", "1 <= nums[i] <= 10^4"],
    starterCode: `/**\n * @param {number[]} nums\n * @return {number}\n */\nvar deleteAndEarn = function(nums) {\n    // Write your code here\n    \n};`,
    solution: `var deleteAndEarn = function(nums) {\n    const maxVal = Math.max(...nums);\n    const points = new Array(maxVal + 1).fill(0);\n    for (const num of nums) points[num] += num;\n    let prev2 = 0, prev1 = points[0];\n    for (let i = 1; i <= maxVal; i++) {\n        const curr = Math.max(prev1, prev2 + points[i]);\n        prev2 = prev1;\n        prev1 = curr;\n    }\n    return prev1;\n};`,
    testCases: [
      { input: "nums = [3,4,2]", expected: "6", args: [[3,4,2]], expectedValue: 6 },
      { input: "nums = [2,2,3,3,3,4]", expected: "9", args: [[2,2,3,3,3,4]], expectedValue: 9 },
      { input: "nums = [1]", expected: "1", args: [[1]], expectedValue: 1 },
    ],
    why: "Reduces to House Robber on frequency-transformed array.",
  },
  {
    id: "minimum-cost-for-tickets",
    patternId: "dp1d",
    name: "Minimum Cost For Tickets",
    difficulty: "Medium",
    number: 983,
    description: `You have planned some train traveling one year in advance. The days of the year on which you will travel are given as an integer array days. Each day is an integer from 1 to 365. Train tickets are sold in three different ways: a 1-day pass for costs[0] dollars, a 7-day pass for costs[1] dollars, and a 30-day pass for costs[2] dollars. Return the minimum number of dollars you need to travel every day in the given list of days.`,
    examples: [
      { input: "days = [1,4,6,7,8,20], costs = [2,7,15]", output: "11", explanation: "Buy a 1-day pass for day 1 (2), a 7-day pass for day 7 (7), and a 1-day pass for day 20 (2). 2+7+2=11." },
      { input: "days = [1,2,3,4,5,6,7,8,9,10,30,31], costs = [2,7,15]", output: "17" },
    ],
    constraints: ["1 <= days.length <= 365", "1 <= days[i] <= 365", "days is strictly increasing.", "costs.length == 3", "1 <= costs[i] <= 1000"],
    starterCode: `/**\n * @param {number[]} days\n * @param {number[]} costs\n * @return {number}\n */\nvar mincostTickets = function(days, costs) {\n    // Write your code here\n    \n};`,
    solution: `var mincostTickets = function(days, costs) {\n    const dp = new Array(366).fill(0);\n    const travel = new Set(days);\n    for (let i = 1; i <= 365; i++) {\n        if (!travel.has(i)) {\n            dp[i] = dp[i - 1];\n        } else {\n            dp[i] = Math.min(\n                dp[Math.max(0, i - 1)] + costs[0],\n                dp[Math.max(0, i - 7)] + costs[1],\n                dp[Math.max(0, i - 30)] + costs[2]\n            );\n        }\n    }\n    return dp[365];\n};`,
    testCases: [
      { input: "days = [1,4,6,7,8,20], costs = [2,7,15]", expected: "11", args: [[1,4,6,7,8,20], [2,7,15]], expectedValue: 11 },
      { input: "days = [1,2,3,4,5,6,7,8,9,10,30,31], costs = [2,7,15]", expected: "17", args: [[1,2,3,4,5,6,7,8,9,10,30,31], [2,7,15]], expectedValue: 17 },
    ],
    why: "dp[i] = min cost to cover all travel days up to day i.",
  },
  {
    id: "best-time-to-buy-and-sell-stock",
    patternId: "dp1d",
    name: "Best Time to Buy and Sell Stock",
    difficulty: "Easy",
    number: 121,
    description: `You are given an array prices where prices[i] is the price of a given stock on the ith day. You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock. Return the maximum profit you can achieve from this transaction. If you cannot achieve any profit, return 0.`,
    examples: [
      { input: "prices = [7,1,5,3,6,4]", output: "5", explanation: "Buy on day 2 (price = 1) and sell on day 5 (price = 6), profit = 6-1 = 5." },
      { input: "prices = [7,6,4,3,1]", output: "0" },
    ],
    constraints: ["1 <= prices.length <= 10^5", "0 <= prices[i] <= 10^4"],
    starterCode: `/**\n * @param {number[]} prices\n * @return {number}\n */\nvar maxProfit = function(prices) {\n    // Write your code here\n    \n};`,
    solution: `var maxProfit = function(prices) {\n    let minPrice = Infinity, maxProfit = 0;\n    for (const price of prices) {\n        if (price < minPrice) minPrice = price;\n        else if (price - minPrice > maxProfit) maxProfit = price - minPrice;\n    }\n    return maxProfit;\n};`,
    testCases: [
      { input: "prices = [7,1,5,3,6,4]", expected: "5", args: [[7,1,5,3,6,4]], expectedValue: 5 },
      { input: "prices = [7,6,4,3,1]", expected: "0", args: [[7,6,4,3,1]], expectedValue: 0 },
      { input: "prices = [2,4,1]", expected: "2", args: [[2,4,1]], expectedValue: 2 },
    ],
    why: "Track minimum price so far; profit at each day is price - min.",
  },
  {
    id: "best-time-to-buy-and-sell-stock-with-cooldown",
    patternId: "dp1d",
    name: "Best Time to Buy and Sell Stock with Cooldown",
    difficulty: "Medium",
    number: 309,
    description: `You are given an array prices where prices[i] is the price of a given stock on the ith day. Find the maximum profit you can achieve. You may complete as many transactions as you like with the following restrictions: After you sell your stock, you cannot buy stock on the next day (i.e., cooldown one day).`,
    examples: [
      { input: "prices = [1,2,3,0,2]", output: "3", explanation: "transactions = [buy, sell, cooldown, buy, sell]" },
      { input: "prices = [1]", output: "0" },
    ],
    constraints: ["1 <= prices.length <= 5000", "0 <= prices[i] <= 1000"],
    starterCode: `/**\n * @param {number[]} prices\n * @return {number}\n */\nvar maxProfit = function(prices) {\n    // Write your code here\n    \n};`,
    solution: `var maxProfit = function(prices) {\n    let sold = 0, held = -Infinity, rested = 0;\n    for (const price of prices) {\n        const prevSold = sold;\n        sold = held + price;\n        held = Math.max(held, rested - price);\n        rested = Math.max(rested, prevSold);\n    }\n    return Math.max(sold, rested);\n};`,
    testCases: [
      { input: "prices = [1,2,3,0,2]", expected: "3", args: [[1,2,3,0,2]], expectedValue: 3 },
      { input: "prices = [1]", expected: "0", args: [[1]], expectedValue: 0 },
      { input: "prices = [1,2,3,0,2,4]", expected: "5", args: [[1,2,3,0,2,4]], expectedValue: 5 },
    ],
    why: "State machine: held, sold, rested track three mutually exclusive states.",
  },
  {
    id: "best-time-to-buy-and-sell-stock-iv",
    patternId: "dp1d",
    name: "Best Time to Buy and Sell Stock IV",
    difficulty: "Hard",
    number: 188,
    description: `You are given an integer array prices where prices[i] is the price of a given stock on the ith day, and an integer k. Find the maximum profit you can achieve. You may complete at most k transactions.`,
    examples: [
      { input: "k = 2, prices = [2,4,1]", output: "2" },
      { input: "k = 2, prices = [3,2,6,5,0,3]", output: "7", explanation: "Buy at 2, sell at 6; buy at 0, sell at 3." },
    ],
    constraints: ["0 <= k <= 100", "0 <= prices.length <= 1000", "0 <= prices[i] <= 1000"],
    starterCode: `/**\n * @param {number} k\n * @param {number[]} prices\n * @return {number}\n */\nvar maxProfit = function(k, prices) {\n    // Write your code here\n    \n};`,
    solution: `var maxProfit = function(k, prices) {\n    if (k === 0 || prices.length === 0) return 0;\n    if (k >= prices.length / 2) {\n        let profit = 0;\n        for (let i = 1; i < prices.length; i++) {\n            if (prices[i] > prices[i - 1]) profit += prices[i] - prices[i - 1];\n        }\n        return profit;\n    }\n    const buy = new Array(k + 1).fill(Infinity);\n    const sell = new Array(k + 1).fill(0);\n    for (const price of prices) {\n        for (let i = 1; i <= k; i++) {\n            buy[i] = Math.min(buy[i], price - sell[i - 1]);\n            sell[i] = Math.max(sell[i], price - buy[i]);\n        }\n    }\n    return sell[k];\n};`,
    testCases: [
      { input: "k = 2, prices = [2,4,1]", expected: "2", args: [2, [2,4,1]], expectedValue: 2 },
      { input: "k = 2, prices = [3,2,6,5,0,3]", expected: "7", args: [2, [3,2,6,5,0,3]], expectedValue: 7 },
      { input: "k = 0, prices = [1,2]", expected: "0", args: [0, [1,2]], expectedValue: 0 },
    ],
    why: "DP with at most k transactions: track best buy/sell per transaction count.",
  },
  {
    id: "integer-break",
    patternId: "dp1d",
    name: "Integer Break",
    difficulty: "Medium",
    number: 343,
    description: `Given an integer n, break it into the sum of k positive integers, where k >= 2, and maximize the product of those integers. Return the maximum product you can get.`,
    examples: [
      { input: "n = 2", output: "1", explanation: "2 = 1 + 1, 1 x 1 = 1." },
      { input: "n = 10", output: "36", explanation: "10 = 3 + 3 + 4, 3 x 3 x 4 = 36." },
    ],
    constraints: ["2 <= n <= 58"],
    starterCode: `/**\n * @param {number} n\n * @return {number}\n */\nvar integerBreak = function(n) {\n    // Write your code here\n    \n};`,
    solution: `var integerBreak = function(n) {\n    const dp = new Array(n + 1).fill(0);\n    dp[1] = 1;\n    for (let i = 2; i <= n; i++) {\n        for (let j = 1; j < i; j++) {\n            dp[i] = Math.max(dp[i], j * dp[i - j], j * (i - j));\n        }\n    }\n    return dp[n];\n};`,
    testCases: [
      { input: "n = 2", expected: "1", args: [2], expectedValue: 1 },
      { input: "n = 10", expected: "36", args: [10], expectedValue: 36 },
      { input: "n = 3", expected: "2", args: [3], expectedValue: 2 },
    ],
    why: "dp[i] = max product from breaking i into at least two positive integers.",
  },
  {
    id: "perfect-squares",
    patternId: "dp1d",
    name: "Perfect Squares",
    difficulty: "Medium",
    number: 279,
    description: `Given an integer n, return the least number of perfect square numbers which sum to n. A perfect square is an integer that is the square of an integer.`,
    examples: [
      { input: "n = 12", output: "3", explanation: "12 = 4 + 4 + 4." },
      { input: "n = 13", output: "2", explanation: "13 = 4 + 9." },
    ],
    constraints: ["1 <= n <= 10^4"],
    starterCode: `/**\n * @param {number} n\n * @return {number}\n */\nvar numSquares = function(n) {\n    // Write your code here\n    \n};`,
    solution: `var numSquares = function(n) {\n    const dp = new Array(n + 1).fill(Infinity);\n    dp[0] = 0;\n    for (let i = 1; i <= n; i++) {\n        for (let j = 1; j * j <= i; j++) {\n            dp[i] = Math.min(dp[i], dp[i - j * j] + 1);\n        }\n    }\n    return dp[n];\n};`,
    testCases: [
      { input: "n = 12", expected: "3", args: [12], expectedValue: 3 },
      { input: "n = 13", expected: "2", args: [13], expectedValue: 2 },
      { input: "n = 1", expected: "1", args: [1], expectedValue: 1 },
    ],
    why: "Unbounded knapsack with square numbers as coin denominations.",
  },
  {
    id: "constrained-subsequence-sum",
    patternId: "dp1d",
    name: "Constrained Subsequence Sum",
    difficulty: "Hard",
    number: 1425,
    description: `Given an integer array nums and an integer k, return the maximum sum of a non-empty subsequence of that array such that for every two consecutive integers in the subsequence, nums[i] and nums[j], where i < j, the condition j - i <= k is satisfied. A subsequence of an array is obtained by deleting some number of elements (can be zero) from the array.`,
    examples: [
      { input: "nums = [10,2,-10,5,20], k = 2", output: "37", explanation: "The subsequence is [10, 2, 5, 20]." },
      { input: "nums = [-1,-2,-3], k = 1", output: "-1" },
    ],
    constraints: ["1 <= k <= nums.length <= 10^5", "-10^4 <= nums[i] <= 10^4"],
    starterCode: `/**\n * @param {number[]} nums\n * @param {number} k\n * @return {number}\n */\nvar constrainedSubsetSum = function(nums, k) {\n    // Write your code here\n    \n};`,
    solution: `var constrainedSubsetSum = function(nums, k) {\n    const dp = new Array(nums.length).fill(0);\n    const deque = [];\n    let max = nums[0];\n    dp[0] = nums[0];\n    deque.push(0);\n    for (let i = 1; i < nums.length; i++) {\n        while (deque.length && deque[0] < i - k) deque.shift();\n        dp[i] = Math.max(0, dp[deque[0]]) + nums[i];\n        max = Math.max(max, dp[i]);\n        while (deque.length && dp[deque.at(-1)] <= dp[i]) deque.pop();\n        deque.push(i);\n    }\n    return max;\n};`,
    testCases: [
      { input: "nums = [10,2,-10,5,20], k = 2", expected: "37", args: [[10,2,-10,5,20], 2], expectedValue: 37 },
      { input: "nums = [-1,-2,-3], k = 1", expected: "-1", args: [[-1,-2,-3], 1], expectedValue: -1 },
      { input: "nums = [10,-2,-10,-5,20], k = 2", expected: "23", args: [[10,-2,-10,-5,20], 2], expectedValue: 23 },
    ],
    why: "Monotonic deque optimizes dp[i] = nums[i] + max(dp[i-k..i-1], 0).",
  },

  // =================== DP 2D ===================
  {
    id: "unique-paths",
    patternId: "dp2d",
    name: "Unique Paths",
    difficulty: "Medium",
    number: 62,
    description: `There is a robot on an m x n grid. The robot is initially located at the top-left corner. The robot tries to move to the bottom-right corner. The robot can only move either down or right at any point in time. Given the two integers m and n, return the number of possible unique paths.`,
    examples: [
      { input: "m = 3, n = 7", output: "28" },
      { input: "m = 3, n = 2", output: "3" },
    ],
    constraints: ["1 <= m, n <= 100"],
    starterCode: `/**\n * @param {number} m\n * @param {number} n\n * @return {number}\n */\nvar uniquePaths = function(m, n) {\n    // Write your code here\n    \n};`,
    solution: `var uniquePaths = function(m, n) {\n    const dp = new Array(n).fill(1);\n    for (let i = 1; i < m; i++) {\n        for (let j = 1; j < n; j++) {\n            dp[j] += dp[j - 1];\n        }\n    }\n    return dp[n - 1];\n};`,
    testCases: [
      { input: "m = 3, n = 7", expected: "28", args: [3, 7], expectedValue: 28 },
      { input: "m = 3, n = 2", expected: "3", args: [3, 2], expectedValue: 3 },
      { input: "m = 1, n = 1", expected: "1", args: [1, 1], expectedValue: 1 },
    ],
    why: "dp[j] = paths from above + paths from left; 1D rolling array.",
  },
  {
    id: "longest-common-subsequence",
    patternId: "dp2d",
    name: "Longest Common Subsequence",
    difficulty: "Medium",
    number: 1143,
    description: `Given two strings text1 and text2, return the length of their longest common subsequence. If there is no common subsequence, return 0. A subsequence of a string is a new string generated from the original string with some characters deleted without changing the relative order.`,
    examples: [
      { input: 'text1 = "abcde", text2 = "ace"', output: "3", explanation: '"ace" is a subsequence of both.' },
      { input: 'text1 = "abc", text2 = "abc"', output: "3" },
    ],
    constraints: ['1 <= text1.length, text2.length <= 1000', 'text1 and text2 consist of only lowercase English characters.'],
    starterCode: `/**\n * @param {string} text1\n * @param {string} text2\n * @return {number}\n */\nvar longestCommonSubsequence = function(text1, text2) {\n    // Write your code here\n    \n};`,
    solution: `var longestCommonSubsequence = function(text1, text2) {\n    const m = text1.length, n = text2.length;\n    const dp = Array.from({ length: m + 1 }, () => new Array(n + 1).fill(0));\n    for (let i = 1; i <= m; i++) {\n        for (let j = 1; j <= n; j++) {\n            if (text1[i - 1] === text2[j - 1]) {\n                dp[i][j] = dp[i - 1][j - 1] + 1;\n            } else {\n                dp[i][j] = Math.max(dp[i - 1][j], dp[i][j - 1]);\n        }\n        }\n    }\n    return dp[m][n];\n};`,
    testCases: [
      { input: 'text1 = "abcde", text2 = "ace"', expected: "3", args: ["abcde", "ace"], expectedValue: 3 },
      { input: 'text1 = "abc", text2 = "def"', expected: "0", args: ["abc", "def"], expectedValue: 0 },
      { input: 'text1 = "abc", text2 = "abc"', expected: "3", args: ["abc", "abc"], expectedValue: 3 },
    ],
    why: "Match extends diagonal; mismatch takes max of top or left.",
  },
  {
    id: "edit-distance",
    patternId: "dp2d",
    name: "Edit Distance",
    difficulty: "Hard",
    number: 72,
    description: `Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2. You have the following three operations permitted on a word: Insert a character, Delete a character, Replace a character.`,
    examples: [
      { input: 'word1 = "horse", word2 = "ros"', output: "3", explanation: 'horse -> rorse (replace h with r), rorse -> rose (remove r), rose -> ros (remove e).' },
      { input: 'word1 = "intention", word2 = "execution"', output: "5" },
    ],
    constraints: ['0 <= word1.length, word2.length <= 500', 'word1 and word2 consist of lowercase English letters.'],
    starterCode: `/**\n * @param {string} word1\n * @param {string} word2\n * @return {number}\n */\nvar minDistance = function(word1, word2) {\n    // Write your code here\n    \n};`,
    solution: `var minDistance = function(word1, word2) {\n    const m = word1.length, n = word2.length;\n    const dp = Array.from({ length: m + 1 }, () => new Array(n + 1).fill(0));\n    for (let i = 0; i <= m; i++) dp[i][0] = i;\n    for (let j = 0; j <= n; j++) dp[0][j] = j;\n    for (let i = 1; i <= m; i++) {\n        for (let j = 1; j <= n; j++) {\n            if (word1[i - 1] === word2[j - 1]) {\n                dp[i][j] = dp[i - 1][j - 1];\n            } else {\n                dp[i][j] = 1 + Math.min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1]);\n            }\n        }\n    }\n    return dp[m][n];\n};`,
    testCases: [
      { input: 'word1 = "horse", word2 = "ros"', expected: "3", args: ["horse", "ros"], expectedValue: 3 },
      { input: 'word1 = "", word2 = ""', expected: "0", args: ["", ""], expectedValue: 0 },
      { input: 'word1 = "a", word2 = "b"', expected: "1", args: ["a", "b"], expectedValue: 1 },
    ],
    why: "Replace/delete/insert: dp[i][j] tracks min edits to transform prefix i to j.",
  },
  {
    id: "minimum-path-sum",
    patternId: "dp2d",
    name: "Minimum Path Sum",
    difficulty: "Medium",
    number: 64,
    description: `Given a m x n grid filled with non-negative numbers, find a path from top left to bottom right, which minimizes the sum of all numbers along its path. You can only move either down or right at any point in time.`,
    examples: [
      { input: "grid = [[1,3,1],[1,5,1],[4,2,1]]", output: "7", explanation: "Path 1→3→1→1→1 minimizes the sum." },
      { input: "grid = [[1,2,3],[4,5,6]]", output: "12" },
    ],
    constraints: ["m == grid.length", "n == grid[i].length", "1 <= m, n <= 200", "0 <= grid[i][j] <= 200"],
    starterCode: `/**\n * @param {number[][]} grid\n * @return {number}\n */\nvar minPathSum = function(grid) {\n    // Write your code here\n    \n};`,
    solution: `var minPathSum = function(grid) {\n    const m = grid.length, n = grid[0].length;\n    const dp = new Array(n).fill(0);\n    dp[0] = grid[0][0];\n    for (let j = 1; j < n; j++) dp[j] = dp[j - 1] + grid[0][j];\n    for (let i = 1; i < m; i++) {\n        dp[0] += grid[i][0];\n        for (let j = 1; j < n; j++) {\n            dp[j] = Math.min(dp[j], dp[j - 1]) + grid[i][j];\n        }\n    }\n    return dp[n - 1];\n};`,
    testCases: [
      { input: "grid = [[1,3,1],[1,5,1],[4,2,1]]", expected: "7", args: [[[1,3,1],[1,5,1],[4,2,1]]], expectedValue: 7 },
      { input: "grid = [[1,2,3],[4,5,6]]", expected: "12", args: [[[1,2,3],[4,5,6]]], expectedValue: 12 },
      { input: "grid = [[1]]", expected: "1", args: [[[1]]], expectedValue: 1 },
    ],
    why: "dp[j] = min path sum to reach cell (i,j) from top or left.",
  },
  {
    id: "triangle",
    patternId: "dp2d",
    name: "Triangle",
    difficulty: "Medium",
    number: 120,
    description: `Given a triangle array, return the minimum path sum from top to bottom. For each step, you may move to an adjacent number of the row below. More formally, if you are on index i on the current row, you may move to either index i or index i + 1 on the next row.`,
    examples: [
      { input: "triangle = [[2],[3,4],[6,5,7],[4,1,8,3]]", output: "11", explanation: "2 + 3 + 5 + 1 = 11." },
      { input: "triangle = [[-10]]", output: "-10" },
    ],
    constraints: ["1 <= triangle.length <= 200", "triangle[0].length == 1", "triangle[i].length == triangle[i - 1].length + 1", "-10^4 <= triangle[i][j] <= 10^4"],
    starterCode: `/**\n * @param {number[][]} triangle\n * @return {number}\n */\nvar minimumTotal = function(triangle) {\n    // Write your code here\n    \n};`,
    solution: `var minimumTotal = function(triangle) {\n    const n = triangle.length;\n    const dp = [...triangle[n - 1]];\n    for (let i = n - 2; i >= 0; i--) {\n        for (let j = 0; j <= i; j++) {\n            dp[j] = triangle[i][j] + Math.min(dp[j], dp[j + 1]);\n        }\n    }\n    return dp[0];\n};`,
    testCases: [
      { input: "triangle = [[2],[3,4],[6,5,7],[4,1,8,3]]", expected: "11", args: [[[2],[3,4],[6,5,7],[4,1,8,3]]], expectedValue: 11 },
      { input: "triangle = [[-10]]", expected: "-10", args: [[[-10]]], expectedValue: -10 },
    ],
    why: "Bottom-up DP: dp[j] = triangle[i][j] + min(dp[j], dp[j+1]).",
  },
  {
    id: "interleaving-string",
    patternId: "dp2d",
    name: "Interleaving String",
    difficulty: "Medium",
    number: 97,
    description: `Given strings s1, s2, and s3, find whether s3 is formed by an interleaving of s1 and s2. An interleaving of two strings s and t is a configuration where s and t are divided into n and m substrings respectively, such that s = s1 + s2 + ... + sn and t = t1 + t2 + ... + tm, and the interleaving is s1 + t1 + s2 + t2 + ... or any other combination that maintains the relative order.`,
    examples: [
      { input: 's1 = "aabcc", s2 = "dbbca", s3 = "aadbbcbcac"', output: "true" },
      { input: 's1 = "aabcc", s2 = "dbbca", s3 = "aadbbbaccc"', output: "false" },
    ],
    constraints: ['0 <= s1.length, s2.length <= 100', '0 <= s3.length <= 200'],
    starterCode: `/**\n * @param {string} s1\n * @param {string} s2\n * @param {string} s3\n * @return {boolean}\n */\nvar isInterleave = function(s1, s2, s3) {\n    // Write your code here\n    \n};`,
    solution: `var isInterleave = function(s1, s2, s3) {\n    if (s1.length + s2.length !== s3.length) return false;\n    const m = s1.length, n = s2.length;\n    const dp = new Array(n + 1).fill(false);\n    dp[0] = true;\n    for (let j = 1; j <= n; j++) dp[j] = dp[j - 1] && s2[j - 1] === s3[j - 1];\n    for (let i = 1; i <= m; i++) {\n        dp[0] = dp[0] && s1[i - 1] === s3[i - 1];\n        for (let j = 1; j <= n; j++) {\n            dp[j] = (dp[j] && s1[i - 1] === s3[i + j - 1]) || (dp[j - 1] && s2[j - 1] === s3[i + j - 1]);\n        }\n    }\n    return dp[n];\n};`,
    testCases: [
      { input: 's1 = "aabcc", s2 = "dbbca", s3 = "aadbbcbcac"', expected: "true", args: ["aabcc", "dbbca", "aadbbcbcac"], expectedValue: true },
      { input: 's1 = "aabcc", s2 = "dbbca", s3 = "aadbbbaccc"', expected: "false", args: ["aabcc", "dbbca", "aadbbbaccc"], expectedValue: false },
      { input: 's1 = "", s2 = "", s3 = ""', expected: "true", args: ["", "", ""], expectedValue: true },
    ],
    why: "dp[i][j] = can s3[0..i+j) be formed from s1[0..i) and s2[0..j).",
  },
  {
    id: "regular-expression-matching",
    patternId: "dp2d",
    name: "Regular Expression Matching",
    difficulty: "Hard",
    number: 10,
    description: `Given an input string s and a pattern p, implement regular expression matching with support for '.' and '*' where '.' Matches any single character and '*' Matches zero or more of the preceding element. The matching should cover the entire input string.`,
    examples: [
      { input: 's = "aa", p = "a"', output: "false", explanation: '"a" does not match the entire string "aa".' },
      { input: 's = "aa", p = "a*"', output: "true", explanation: '"*" means zero or more of the preceding element, "a".' },
      { input: 's = "ab", p = ".*"', output: "true", explanation: '".*" means "zero or more (*) of any character (.)."' },
    ],
    constraints: ['1 <= s.length <= 20', '1 <= p.length <= 30'],
    starterCode: `/**\n * @param {string} s\n * @param {string} p\n * @return {boolean}\n */\nvar isMatch = function(s, p) {\n    // Write your code here\n    \n};`,
    solution: `var isMatch = function(s, p) {\n    const m = s.length, n = p.length;\n    const dp = Array.from({ length: m + 1 }, () => new Array(n + 1).fill(false));\n    dp[0][0] = true;\n    for (let j = 2; j <= n; j++) {\n        if (p[j - 1] === '*') dp[0][j] = dp[0][j - 2];\n    }\n    for (let i = 1; i <= m; i++) {\n        for (let j = 1; j <= n; j++) {\n            if (p[j - 1] === '.' || p[j - 1] === s[i - 1]) {\n                dp[i][j] = dp[i - 1][j - 1];\n            } else if (p[j - 1] === '*') {\n                dp[i][j] = dp[i][j - 2];\n                if (p[j - 2] === '.' || p[j - 2] === s[i - 1]) {\n                    dp[i][j] = dp[i][j] || dp[i - 1][j];\n                }\n            }\n        }\n    }\n    return dp[m][n];\n};`,
    testCases: [
      { input: 's = "aa", p = "a"', expected: "false", args: ["aa", "a"], expectedValue: false },
      { input: 's = "aa", p = "a*"', expected: "true", args: ["aa", "a*"], expectedValue: true },
      { input: 's = "ab", p = ".*"', expected: "true", args: ["ab", ".*"], expectedValue: true },
    ],
    why: "dp[i][j] handles literal match, '.', and '*' with zero/one/many semantics.",
  },
  {
    id: "wildcard-matching",
    patternId: "dp2d",
    name: "Wildcard Matching",
    difficulty: "Hard",
    number: 44,
    description: `Given an input string s and a pattern p, implement wildcard pattern matching with support for '?' and '*' where '?' Matches any single character and '*' Matches any sequence of characters (including the empty sequence). The matching should cover the entire input string.`,
    examples: [
      { input: 's = "aa", p = "a"', output: "false" },
      { input: 's = "aa", p = "*"', output: "true", explanation: '"*" matches any sequence.' },
      { input: 's = "cb", p = "?a"', output: "false" },
    ],
    constraints: ['0 <= s.length, p.length <= 2000', 's contains only lowercase English letters.', 'p contains only lowercase English letters, ? or *.'],
    starterCode: `/**\n * @param {string} s\n * @param {string} p\n * @return {boolean}\n */\nvar isMatch = function(s, p) {\n    // Write your code here\n    \n};`,
    solution: `var isMatch = function(s, p) {\n    const m = s.length, n = p.length;\n    const dp = Array.from({ length: m + 1 }, () => new Array(n + 1).fill(false));\n    dp[0][0] = true;\n    for (let j = 1; j <= n; j++) {\n        if (p[j - 1] === '*') dp[0][j] = dp[0][j - 1];\n    }\n    for (let i = 1; i <= m; i++) {\n        for (let j = 1; j <= n; j++) {\n            if (p[j - 1] === '*') {\n                dp[i][j] = dp[i][j - 1] || dp[i - 1][j];\n            } else if (p[j - 1] === '?' || p[j - 1] === s[i - 1]) {\n                dp[i][j] = dp[i - 1][j - 1];\n            }\n        }\n    }\n    return dp[m][n];\n};`,
    testCases: [
      { input: 's = "aa", p = "a"', expected: "false", args: ["aa", "a"], expectedValue: false },
      { input: 's = "aa", p = "*"', expected: "true", args: ["aa", "*"], expectedValue: true },
      { input: 's = "abcdef", p = "a*ef"', expected: "true", args: ["abcdef", "a*ef"], expectedValue: true },
    ],
    why: "'*' can match empty or consume one char; '?' matches exactly one.",
  },
  {
    id: "maximal-square",
    patternId: "dp2d",
    name: "Maximal Square",
    difficulty: "Medium",
    number: 221,
    description: `Given an m x n binary matrix filled with 0's and 1's, find the largest square containing only 1's and return its area.`,
    examples: [
      { input: 'matrix = [["1","0","1","0","0"],["1","0","1","1","1"],["1","1","1","1","1"],["1","0","0","1","0"]]', output: "4" },
      { input: 'matrix = [["0","1"],["1","0"]]', output: "1" },
    ],
    constraints: ['m == matrix.length', 'n == matrix[0].length', '1 <= m, n <= 300', 'matrix[i][j] is "0" or "1".'],
    starterCode: `/**\n * @param {character[][]} matrix\n * @return {number}\n */\nvar maximalSquare = function(matrix) {\n    // Write your code here\n    \n};`,
    solution: `var maximalSquare = function(matrix) {\n    if (!matrix.length) return 0;\n    const m = matrix.length, n = matrix[0].length;\n    const dp = Array.from({ length: m + 1 }, () => new Array(n + 1).fill(0));\n    let max = 0;\n    for (let i = 1; i <= m; i++) {\n        for (let j = 1; j <= n; j++) {\n            if (matrix[i - 1][j - 1] === "1") {\n                dp[i][j] = Math.min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1]) + 1;\n                max = Math.max(max, dp[i][j]);\n            }\n        }\n    }\n    return max * max;\n};`,
    testCases: [
      { input: 'matrix = [["1","0","1","0","0"],["1","0","1","1","1"],["1","1","1","1","1"],["1","0","0","1","0"]]', expected: "4", args: [[["1","0","1","0","0"],["1","0","1","1","1"],["1","1","1","1","1"],["1","0","0","1","0"]]], expectedValue: 4 },
      { input: 'matrix = [["0"]]', expected: "0", args: [[["0"]]], expectedValue: 0 },
    ],
    why: "dp[i][j] = side length of largest square of 1s ending at (i,j).",
  },
  {
    id: "dungeon-game",
    patternId: "dp2d",
    name: "Dungeon Game",
    difficulty: "Hard",
    number: 174,
    description: `The demons had captured the princess and imprisoned her in the bottom-right corner of a dungeon. The dungeon consists of m x n rooms laid out in a 2D grid. Our valiant knight was initially positioned in the top-left room and must fight his way through dungeon to rescue the princess. The knight has an initial health point. If his health point drops to 0 or below, he dies immediately. Some rooms are guarded by demons, so the knight loses health; other rooms are either empty or contain magic orbs that increase the knight's health. To reach the princess as quickly as possible, the knight moves only rightward or downward in each step. Return the knight's minimum initial health so that he can rescue the princess.`,
    examples: [
      { input: "dungeon = [[-2,-3,3],[-5,-10,1],[10,30,-5]]", output: "7", explanation: "Minimum initial health = 7." },
      { input: "dungeon = [[0]]", output: "1" },
    ],
    constraints: ["m == dungeon.length", "n == dungeon[i].length", "1 <= m, n <= 200", "-1000 <= dungeon[i][j] <= 1000"],
    starterCode: `/**\n * @param {number[][]} dungeon\n * @return {number}\n */\nvar calculateMinimumHP = function(dungeon) {\n    // Write your code here\n    \n};`,
    solution: `var calculateMinimumHP = function(dungeon) {\n    const m = dungeon.length, n = dungeon[0].length;\n    const dp = new Array(n).fill(Infinity);\n    dp[n - 1] = 1;\n    for (let i = m - 1; i >= 0; i--) {\n        dp[n - 1] = Math.max(1, dp[n - 1] - dungeon[i][n - 1]);\n        for (let j = n - 2; j >= 0; j--) {\n            dp[j] = Math.max(1, Math.min(dp[j], dp[j + 1]) - dungeon[i][j]);\n        }\n    }\n    return dp[0];\n};`,
    testCases: [
      { input: "dungeon = [[-2,-3,3],[-5,-10,1],[10,30,-5]]", expected: "7", args: [[[-2,-3,3],[-5,-10,1],[10,30,-5]]], expectedValue: 7 },
      { input: "dungeon = [[0]]", expected: "1", args: [[[0]]], expectedValue: 1 },
    ],
    why: "Bottom-up: dp[j] = min health needed at (i,j) to survive to princess.",
  },
  {
    id: "distinct-subsequences",
    patternId: "dp2d",
    name: "Distinct Subsequences",
    difficulty: "Hard",
    number: 115,
    description: `Given two strings s and t, return the number of distinct subsequences of s which equals t. A string's subsequence is a new string formed from the original string by deleting some (can be none) of the characters without disturbing the remaining characters' relative positions.`,
    examples: [
      { input: 's = "rabbbit", t = "rabbit"', output: "3" },
      { input: 's = "babgbag", t = "bag"', output: "5" },
    ],
    constraints: ['1 <= s.length, t.length <= 1000', 's and t consist of English letters.'],
    starterCode: `/**\n * @param {string} s\n * @param {string} t\n * @return {number}\n */\nvar numDistinct = function(s, t) {\n    // Write your code here\n    \n};`,
    solution: `var numDistinct = function(s, t) {\n    const m = s.length, n = t.length;\n    const dp = new Array(n + 1).fill(0);\n    dp[0] = 1;\n    for (let i = 1; i <= m; i++) {\n        for (let j = n; j >= 1; j--) {\n            if (s[i - 1] === t[j - 1]) dp[j] += dp[j - 1];\n        }\n    }\n    return dp[n];\n};`,
    testCases: [
      { input: 's = "rabbbit", t = "rabbit"', expected: "3", args: ["rabbbit", "rabbit"], expectedValue: 3 },
      { input: 's = "babgbag", t = "bag"', expected: "5", args: ["babgbag", "bag"], expectedValue: 5 },
      { input: 's = "", t = ""', expected: "1", args: ["", ""], expectedValue: 1 },
    ],
    why: "dp[j] = count of t[0..j) as subsequence in s processed so far.",
  },
  {
    id: "longest-palindromic-subsequence",
    patternId: "dp2d",
    name: "Longest Palindromic Subsequence",
    difficulty: "Medium",
    number: 516,
    description: `Given a string s, find the longest palindromic subsequence's length in s. A subsequence is a sequence that can be derived from another sequence by deleting some or no elements without changing the order of the remaining elements.`,
    examples: [
      { input: 's = "bbbab"', output: "4", explanation: '"bbbb".' },
      { input: 's = "cbbd"', output: "2", explanation: '"bb".' },
    ],
    constraints: ['1 <= s.length <= 1000', 's consists only of lowercase English letters.'],
    starterCode: `/**\n * @param {string} s\n * @return {number}\n */\nvar longestPalindromeSubseq = function(s) {\n    // Write your code here\n    \n};`,
    solution: `var longestPalindromeSubseq = function(s) {\n    const n = s.length;\n    const dp = Array.from({ length: n }, () => new Array(n).fill(0));\n    for (let i = n - 1; i >= 0; i--) {\n        dp[i][i] = 1;\n        for (let j = i + 1; j < n; j++) {\n            if (s[i] === s[j]) {\n                dp[i][j] = dp[i + 1][j - 1] + 2;\n            } else {\n                dp[i][j] = Math.max(dp[i + 1][j], dp[i][j - 1]);\n            }\n        }\n    }\n    return dp[0][n - 1];\n};`,
    testCases: [
      { input: 's = "bbbab"', expected: "4", args: ["bbbab"], expectedValue: 4 },
      { input: 's = "cbbd"', expected: "2", args: ["cbbd"], expectedValue: 2 },
      { input: 's = "a"', expected: "1", args: ["a"], expectedValue: 1 },
    ],
    why: "Match extends by 2 from inner diagonal; mismatch takes max of inner ranges.",
  },
  {
    id: "burst-balloons",
    patternId: "dp2d",
    name: "Burst Balloons",
    difficulty: "Hard",
    number: 312,
    description: `You are given n balloons, indexed from 0 to n - 1. Each balloon is painted with a number on it represented by an array nums. You are asked to burst all the balloons. If you burst the ith balloon, you will get nums[i - 1] * nums[i] * nums[i + 1] coins. If i - 1 or i + 1 goes out of bounds of the array, then treat it as if there is a balloon with a 1 painted on it. Return the maximum coins you can collect by bursting the balloons wisely.`,
    examples: [
      { input: "nums = [3,1,5,8]", output: "167", explanation: "Burst in order: 1, 5, 3, 8. Coins: 3*1*5 + 3*5*8 + 1*3*8 + 1*8*1 = 167." },
      { input: "nums = [1,5]", output: "10" },
    ],
    constraints: ["n == nums.length", "1 <= n <= 500", "0 <= nums[i] <= 100"],
    starterCode: `/**\n * @param {number[]} nums\n * @return {number}\n */\nvar maxCoins = function(nums) {\n    // Write your code here\n    \n};`,
    solution: `var maxCoins = function(nums) {\n    const arr = [1, ...nums, 1];\n    const n = arr.length;\n    const dp = Array.from({ length: n }, () => new Array(n).fill(0));\n    for (let len = 2; len < n; len++) {\n        for (let left = 0; left < n - len; left++) {\n            const right = left + len;\n            for (let i = left + 1; i < right; i++) {\n                dp[left][right] = Math.max(\n                    dp[left][right],\n                    dp[left][i] + dp[i][right] + arr[left] * arr[i] * arr[right]\n                );\n            }\n        }\n    }\n    return dp[0][n - 1];\n};`,
    testCases: [
      { input: "nums = [3,1,5,8]", expected: "167", args: [[3,1,5,8]], expectedValue: 167 },
      { input: "nums = [1,5]", expected: "10", args: [[1,5]], expectedValue: 10 },
      { input: "nums = [9]", expected: "9", args: [[9]], expectedValue: 9 },
    ],
    why: "Interval DP: dp[left][right] = max coins from bursting all balloons between them.",
  },
  {
    id: "minimum-falling-path-sum",
    patternId: "dp2d",
    name: "Minimum Falling Path Sum",
    difficulty: "Medium",
    number: 931,
    description: `Given an n x n array of integers matrix, return the minimum sum of any falling path through matrix. A falling path starts at any element in the first row and chooses the element in the next row that is either directly below or diagonally left/right.`,
    examples: [
      { input: "matrix = [[2,1,3],[6,5,4],[7,8,9]]", output: "13", explanation: "Falling path: 1 -> 5 -> 7." },
      { input: "matrix = [[-19,57],[-40,-5]]", output: "-59", explanation: "Falling path: -19 -> -40." },
    ],
    constraints: ["n == matrix.length == matrix[i].length", "1 <= n <= 100", "-100 <= matrix[i][j] <= 100"],
    starterCode: `/**\n * @param {number[][]} matrix\n * @return {number}\n */\nvar minFallingPathSum = function(matrix) {\n    // Write your code here\n    \n};`,
    solution: `var minFallingPathSum = function(matrix) {\n    const n = matrix.length;\n    const dp = [...matrix[0]];\n    for (let i = 1; i < n; i++) {\n        const prev = [...dp];\n        for (let j = 0; j < n; j++) {\n            let min = prev[j];\n            if (j > 0) min = Math.min(min, prev[j - 1]);\n            if (j < n - 1) min = Math.min(min, prev[j + 1]);\n            dp[j] = min + matrix[i][j];\n        }\n    }\n    return Math.min(...dp);\n};`,
    testCases: [
      { input: "matrix = [[2,1,3],[6,5,4],[7,8,9]]", expected: "13", args: [[[2,1,3],[6,5,4],[7,8,9]]], expectedValue: 13 },
      { input: "matrix = [[-19,57],[-40,-5]]", expected: "-59", args: [[[-19,57],[-40,-5]]], expectedValue: -59 },
    ],
    why: "dp[j] = min falling sum to reach column j in current row from above neighbors.",
  },
  {
    id: "partition-array-for-maximum-sum",
    patternId: "dp2d",
    name: "Partition Array for Maximum Sum",
    difficulty: "Medium",
    number: 1043,
    description: `Given an integer array arr, you should partition the array into (contiguous) subarrays of length at most k. After partitioning, each subarray has their values changed to become the maximum value of that subarray. Return the largest sum of the given array after partitioning.`,
    examples: [
      { input: "arr = [1,15,7,9,2,5,10], k = 3", output: "84", explanation: "Partition into [1,15,7], [9], [2,5,10]. Sum = 15*3 + 9 + 10*3 = 84." },
      { input: "arr = [1,4,1,5,7,3,6,1,9,9,3], k = 4", output: "83" },
    ],
    constraints: ["n == arr.length", "1 <= n <= 500", "0 <= arr[i] <= 10^9", "1 <= k <= n"],
    starterCode: `/**\n * @param {number[]} arr\n * @param {number} k\n * @return {number}\n */\nvar maxSumAfterPartitioning = function(arr, k) {\n    // Write your code here\n    \n};`,
    solution: `var maxSumAfterPartitioning = function(arr, k) {\n    const n = arr.length;\n    const dp = new Array(n + 1).fill(0);\n    for (let i = 1; i <= n; i++) {\n        let max = 0;\n        for (let j = 1; j <= k && i - j >= 0; j++) {\n            max = Math.max(max, arr[i - j]);\n            dp[i] = Math.max(dp[i], dp[i - j] + max * j);\n        }\n    }\n    return dp[n];\n};`,
    testCases: [
      { input: "arr = [1,15,7,9,2,5,10], k = 3", expected: "84", args: [[1,15,7,9,2,5,10], 3], expectedValue: 84 },
      { input: "arr = [1,4,1,5,7,3,6,1,9,9,3], k = 4", expected: "83", args: [[1,4,1,5,7,3,6,1,9,9,3], 4], expectedValue: 83 },
    ],
    why: "dp[i] = max sum for arr[0..i); try all partition sizes up to k ending at i.",
  },
  {
    id: "stone-game",
    patternId: "dp2d",
    name: "Stone Game",
    difficulty: "Medium",
    number: 877,
    description: `Alice and Bob play a game with piles of stones arranged in a row. Alice always starts. On each player's turn, they can take the entire pile from the beginning or the end. Return true if Alice wins the game, or false if Bob wins. Both play optimally.`,
    examples: [
      { input: "piles = [5,3,4,5]", output: "true", explanation: "Alice starts first, taking 5 from left." },
    ],
    constraints: ["2 <= piles.length <= 500", "piles.length is even.", "1 <= piles[i] <= 500", "sum(piles) is odd."],
    starterCode: `/**\n * @param {number[]} piles\n * @return {boolean}\n */\nvar stoneGame = function(piles) {\n    // Write your code here\n    \n};`,
    solution: `var stoneGame = function(piles) {\n    return true;\n};`,
    testCases: [
      { input: "piles = [5,3,4,5]", expected: "true", args: [[5,3,4,5]], expectedValue: true },
      { input: "piles = [3,7,2,3]", expected: "true", args: [[3,7,2,3]], expectedValue: true },
    ],
    why: "Alice always wins with even piles and optimal play (math proof).",
  },
  {
    id: "stone-game-ii",
    patternId: "dp2d",
    name: "Stone Game II",
    difficulty: "Medium",
    number: 1563,
    description: `Alice and Bob continue their games with piles of stones. There are several stones arranged in a row, and each stone has an associated value. Alice and Bob take turns, with Alice starting first. On each player's turn, they can take 1 <= X <= 2M piles, then M is updated to max(M, X). Return the maximum number of stones Alice can get.`,
    examples: [
      { input: "piles = [2,7,9,4,4]", output: "10", explanation: "If Alice takes one pile, M becomes 1." },
      { input: "piles = [1,2,3,4,5,100]", output: "104" },
    ],
    constraints: ["1 <= piles.length <= 100", "1 <= piles[i] <= 10^4"],
    starterCode: `/**\n * @param {number[]} piles\n * @return {number}\n */\nvar stoneGameII = function(piles) {\n    // Write your code here\n    \n};`,
    solution: `var stoneGameII = function(piles) {\n    const n = piles.length;\n    const suffix = new Array(n + 1).fill(0);\n    for (let i = n - 1; i >= 0; i--) suffix[i] = suffix[i + 1] + piles[i];\n    const dp = Array.from({ length: n }, () => new Array(n + 1).fill(0));\n    for (let i = n - 1; i >= 0; i--) {\n        for (let m = 1; m <= n; m++) {\n            if (i + 2 * m >= n) {\n                dp[i][m] = suffix[i];\n            } else {\n                for (let x = 1; x <= 2 * m; x++) {\n                    dp[i][m] = Math.max(dp[i][m], suffix[i] - dp[i + x][Math.max(m, x)]);\n                }\n            }\n        }\n    }\n    return dp[0][1];\n};`,
    testCases: [
      { input: "piles = [2,7,9,4,4]", expected: "10", args: [[2,7,9,4,4]], expectedValue: 10 },
      { input: "piles = [1,2,3,4,5,100]", expected: "104", args: [[1,2,3,4,5,100]], expectedValue: 104 },
    ],
    why: "dp[i][m] = max stones from piles[i..n) with current M = m.",
  },
  {
    id: "cherry-pickup",
    patternId: "dp2d",
    name: "Cherry Pickup",
    difficulty: "Hard",
    number: 741,
    description: `You are given an n x n grid representing a field of cherries, each cell is one of three possible integers. 0 means the cell is empty, 1 means the cell contains a cherry, and -1 means the cell contains a thorn that blocks your access. Return the maximum number of cherries you can collect by following the rules: Start at (0, 0) and reach (n - 1, n - 1) by moving right or down, then return to (0, 0) by moving left or up. When passing through a cell with a cherry, you pick it up and the cell becomes empty. If there is no valid path between (0, 0) and (n - 1, n - 1), then no cherries can be collected.`,
    examples: [
      { input: "grid = [[0,1,-1],[1,0,-1],[1,1,1]]", output: "5", explanation: "Pick 1, 1, 1, 1, 1." },
      { input: "grid = [[1,1,-1],[1,-1,1],[-1,1,1]]", output: "0" },
    ],
    constraints: ["n == grid.length", "n == grid[i].length", "1 <= n <= 50", "grid[i][j] is -1, 0, or 1."],
    starterCode: `/**\n * @param {number[][]} grid\n * @return {number}\n */\nvar cherryPickup = function(grid) {\n    // Write your code here\n    \n};`,
    solution: `var cherryPickup = function(grid) {\n    const n = grid.length;\n    const dp = Array.from({ length: n }, () => Array.from({ length: n }, () => new Array(n).fill(-Infinity)));\n    dp[0][0][0] = grid[0][0];\n    for (let s = 1; s <= 2 * (n - 1); s++) {\n        for (let x1 = Math.max(0, s - (n - 1)); x1 <= Math.min(n - 1, s); x1++) {\n            for (let x2 = x1; x2 <= Math.min(n - 1, s); x2++) {\n                const y1 = s - x1, y2 = s - x2;\n                if (y1 < 0 || y1 >= n || y2 < 0 || y2 >= n) continue;\n                if (grid[x1][y1] === -1 || grid[x2][y2] === -1) {\n                    dp[x1][y2][x2] = -Infinity;\n                    continue;\n                }\n                let best = -Infinity;\n                if (x1 > 0 && x2 > 0) best = Math.max(best, dp[x1 - 1][y1][x2 - 1]);\n                if (x1 > 0 && y2 > 0) best = Math.max(best, dp[x1 - 1][y1][x2]);\n                if (y1 > 0 && x2 > 0) best = Math.max(best, dp[x1][y1 - 1][x2 - 1]);\n                if (y1 > 0 && y2 > 0) best = Math.max(best, dp[x1][y1 - 1][x2]);\n                if (best === -Infinity) continue;\n                let gain = grid[x1][y1];\n                if (x1 !== x2) gain += grid[x2][y2];\n                dp[x1][y2][x2] = best + gain;\n            }\n        }\n    }\n    return Math.max(0, dp[n - 1][n - 1][n - 1]);\n};`,
    testCases: [
      { input: "grid = [[0,1,-1],[1,0,-1],[1,1,1]]", expected: "5", args: [[[0,1,-1],[1,0,-1],[1,1,1]]], expectedValue: 5 },
      { input: "grid = [[1,1,-1],[1,-1,1],[-1,1,1]]", expected: "0", args: [[[1,1,-1],[1,-1,1],[-1,1,1]]], expectedValue: 0 },
      { input: "grid = [[1]]", expected: "1", args: [[[1]]], expectedValue: 1 },
    ],
    why: "Simultaneous round-trip DP: two walkers from (0,0) to (n-1,n-1).",
  },
];
